using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace BitPack.Generator;

[Generator]
public class PacketGenerator : IIncrementalGenerator
{
    private static readonly DiagnosticDescriptor UnsupportedTypeError = new(
        "BP0001",
        "Unsupported Property Type",
        "Property '{0}' of type '{1}' must be annotated with [BitPacket] or implement custom serialization (Serialize and static Deserialize)",
        "BitPackGenerator",
        DiagnosticSeverity.Error,
        true);

    private static readonly DiagnosticDescriptor UnconstrainedPropertyWarning = new(
        "BP0002",
        "Unconstrained Property Warning",
        "Property '{0}' of type '{1}' does not specify a range or length attribute. Full type storage will be used, which is unoptimized.",
        "BitPackGenerator",
        DiagnosticSeverity.Warning,
        true);

    private static readonly DiagnosticDescriptor BitFieldKeyError = new(
        "BP0003",
        "Invalid BitFieldKey",
        "Property or field '{0}' has invalid BitFieldKey: {1}",
        "BitPackGenerator",
        DiagnosticSeverity.Error,
        true);

    private static readonly DiagnosticDescriptor BoundedArrayError = new(
        "BP0004",
        "Invalid Bounded Array",
        "Array property or field '{0}' has invalid bounds: {1}",
        "BitPackGenerator",
        DiagnosticSeverity.Error,
        true);

    private static readonly DiagnosticDescriptor MathCodecError = new(
        "BP0005",
        "Invalid Game Math Codec",
        "Property or field '{0}' has invalid game math codec: {1}",
        "BitPackGenerator",
        DiagnosticSeverity.Error,
        true);

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var packetDeclarations = context.SyntaxProvider
            .CreateSyntaxProvider(
                static (s, _) => s is TypeDeclarationSyntax tds && tds.AttributeLists.Count > 0,
                static (ctx, _) => GetSemanticTargetForGeneration(ctx))
            .Where(static m => m is not null);

        context.RegisterSourceOutput(packetDeclarations, static (spc, source) => Execute(spc, source!));
    }

    private static ITypeSymbol? GetSemanticTargetForGeneration(GeneratorSyntaxContext context)
    {
        var typeDeclarationSyntax = (TypeDeclarationSyntax)context.Node;

        foreach (var attributeListSyntax in typeDeclarationSyntax.AttributeLists)
        foreach (var attributeSyntax in attributeListSyntax.Attributes)
        {
            var symbol = context.SemanticModel.GetSymbolInfo(attributeSyntax).Symbol;
            if (symbol is IMethodSymbol attributeConstructor)
            {
                var attributeContainingTypeSymbol = attributeConstructor.ContainingType;
                var fullName = attributeContainingTypeSymbol.ToDisplayString();

                if (fullName == "BitPack.BitPacketAttribute")
                    return context.SemanticModel.GetDeclaredSymbol(typeDeclarationSyntax) as ITypeSymbol;
            }
        }

        return null;
    }

    private static void Execute(SourceProductionContext context, ITypeSymbol typeSymbol)
    {
        if (typeSymbol.IsAbstract)
        {
            context.ReportDiagnostic(Diagnostic.Create(
                UnsupportedTypeError,
                typeSymbol.Locations.FirstOrDefault(),
                typeSymbol.Name,
                "Abstract types cannot be marked with [BitPacket]. Mark only concrete packet types; inherited base members are included automatically."));
            return;
        }

        var namespaceName = typeSymbol.ContainingNamespace.IsGlobalNamespace
            ? string.Empty
            : typeSymbol.ContainingNamespace.ToDisplayString();

        var typeName = typeSymbol.Name;

        var typeKeyword = "class";
        if (typeSymbol.IsRecord)
            typeKeyword = typeSymbol.IsValueType ? "record struct" : "record";
        else if (typeSymbol.IsValueType) typeKeyword = "struct";

        var targets = GetSerializationTargets(typeSymbol);
        ValidateTargetSafety(context, typeSymbol, targets);

        var sourceBuilder = new StringBuilder();
        sourceBuilder.AppendLine("// <auto-generated/>");
        sourceBuilder.AppendLine("using System;");
        sourceBuilder.AppendLine("using BitPack;");
        sourceBuilder.AppendLine();

        if (!string.IsNullOrEmpty(namespaceName))
        {
            sourceBuilder.AppendLine($"namespace {namespaceName};");
            sourceBuilder.AppendLine();
        }

        sourceBuilder.AppendLine($"public partial {typeKeyword} {typeName} : IBitSerializable");
        sourceBuilder.AppendLine("{");

        // Retrieve packet version
        var packetMaxVersion = GetPacketVersion(typeSymbol);
        var hasVersionedTargets = targets.Any(t => GetPropertyVersion(t.Symbol) > 1);
        var maxBits = GetPacketMaxBits(typeSymbol, targets, packetMaxVersion);
        var maxBytes = maxBits < 0 ? -1 : (maxBits + 7) / 8;
        var layoutManifest = BuildLayoutManifest(typeSymbol, targets, packetMaxVersion, maxBits, maxBytes);
        var layoutHash = ComputeFnv1A32(layoutManifest);

        sourceBuilder.AppendLine($"    public const int MaxBits = {maxBits};");
        sourceBuilder.AppendLine($"    public const int MaxBytes = {maxBytes};");
        sourceBuilder.AppendLine($"    public const uint LayoutHash = 0x{layoutHash:X8}u;");
        sourceBuilder.AppendLine($"    public const string LayoutManifest = \"{EscapeStringLiteral(layoutManifest)}\";");
        sourceBuilder.AppendLine();

        // Generate Serialize method
        sourceBuilder.AppendLine("    public void Serialize(BitWriter writer)");
        sourceBuilder.AppendLine("    {");
        if (packetMaxVersion > 1) sourceBuilder.AppendLine($"        writer.WriteInt({packetMaxVersion}, 4);");

        GenerateSerializationLoop(context, sourceBuilder, typeSymbol, targets, true, packetMaxVersion, false);
        sourceBuilder.AppendLine("    }");
        sourceBuilder.AppendLine();

        sourceBuilder.AppendLine("    public void SerializeUnchecked(BitWriter writer)");
        sourceBuilder.AppendLine("    {");
        if (packetMaxVersion > 1) sourceBuilder.AppendLine($"        writer.WriteInt({packetMaxVersion}, 4);");
        GenerateSerializationLoop(context, sourceBuilder, typeSymbol, targets, true, packetMaxVersion, true);
        sourceBuilder.AppendLine("    }");
        sourceBuilder.AppendLine();

        sourceBuilder.AppendLine("    public bool TrySerialize(byte[] buffer, out int bytesWritten)");
        sourceBuilder.AppendLine("    {");
        sourceBuilder.AppendLine("        bytesWritten = 0;");
        sourceBuilder.AppendLine("        if (buffer == null) return false;");
        if (maxBytes >= 0)
            sourceBuilder.AppendLine($"        if (buffer.Length < {maxBytes}) return false;");
        sourceBuilder.AppendLine("        var writer = new BitWriter(buffer);");
        sourceBuilder.AppendLine("        try");
        sourceBuilder.AppendLine("        {");
        sourceBuilder.AppendLine("            Serialize(writer);");
        sourceBuilder.AppendLine("            bytesWritten = writer.BytesWritten;");
        sourceBuilder.AppendLine("            return true;");
        sourceBuilder.AppendLine("        }");
        sourceBuilder.AppendLine("        catch (ArgumentOutOfRangeException)");
        sourceBuilder.AppendLine("        {");
        sourceBuilder.AppendLine("            bytesWritten = 0;");
        sourceBuilder.AppendLine("            return false;");
        sourceBuilder.AppendLine("        }");
        sourceBuilder.AppendLine("        catch (IndexOutOfRangeException)");
        sourceBuilder.AppendLine("        {");
        sourceBuilder.AppendLine("            bytesWritten = 0;");
        sourceBuilder.AppendLine("            return false;");
        sourceBuilder.AppendLine("        }");
        sourceBuilder.AppendLine("    }");
        sourceBuilder.AppendLine();

        // Generate Deserialize method
        sourceBuilder.AppendLine("    public void Deserialize(BitReader reader)");
        sourceBuilder.AppendLine("    {");
        if (packetMaxVersion > 1)
            sourceBuilder.AppendLine(hasVersionedTargets
                ? "        var packetVersion = reader.ReadInt(4);"
                : "        reader.ReadInt(4);");
        else if (hasVersionedTargets) sourceBuilder.AppendLine("        var packetVersion = 1;");

        GenerateSerializationLoop(context, sourceBuilder, typeSymbol, targets, false, packetMaxVersion, false);
        sourceBuilder.AppendLine("    }");


        // Generate static Read factory method (enables clean nested deserialization)
        sourceBuilder.AppendLine();
        sourceBuilder.AppendLine($"    public static {typeName} Read(BitReader reader)");
        sourceBuilder.AppendLine("    {");
        if (packetMaxVersion > 1)
            sourceBuilder.AppendLine(hasVersionedTargets
                ? "        var packetVersion = reader.ReadInt(4);"
                : "        reader.ReadInt(4);");
        else if (hasVersionedTargets)
            sourceBuilder.AppendLine("        var packetVersion = 1;");

        // 1. Declare read variables with defaults
        foreach (var target in targets)
            sourceBuilder.AppendLine($"        var read_{target.Name} = default({target.Type.ToDisplayString()});");

        sourceBuilder.AppendLine();

        // 2. Read variables from bitstream using target-agnostic generator
        foreach (var target in targets)
        {
            var propVersion = GetPropertyVersion(target.Symbol);
            var propSb = new StringBuilder();
            GeneratePropertySerialization(context, propSb, target, false, $"read_{target.Name}");

            if (propVersion > 1)
            {
                sourceBuilder.AppendLine($"        if (packetVersion >= {propVersion})");
                sourceBuilder.AppendLine("        {");
                foreach (var line in propSb.ToString().Split(new[] { "\r\n", "\n" }, StringSplitOptions.None))
                    if (!string.IsNullOrWhiteSpace(line))
                        sourceBuilder.AppendLine("    " + line);

                sourceBuilder.AppendLine("        }");
            }
            else
            {
                sourceBuilder.Append(propSb);
            }
        }

        sourceBuilder.AppendLine();

        // 3. Resolve constructor
        var ctor = FindMatchingConstructor(typeSymbol as INamedTypeSymbol, targets, out var ctorArgs);
        if (ctor != null)
        {
            sourceBuilder.Append($"        var packet = new {typeName}(");
            for (var i = 0; i < ctorArgs.Count; i++)
            {
                sourceBuilder.Append($"read_{ctorArgs[i].Name}");
                if (i < ctorArgs.Count - 1)
                    sourceBuilder.Append(", ");
            }

            sourceBuilder.AppendLine(")");
            sourceBuilder.AppendLine("        {");
            foreach (var target in targets)
                if (!ctorArgs.Contains(target) && IsWritablePropertyForInitializer(target.Symbol))
                    sourceBuilder.AppendLine($"            {target.Name} = read_{target.Name},");

            sourceBuilder.AppendLine("        };");
        }
        else
        {
            sourceBuilder.AppendLine($"        var packet = new {typeName}");
            sourceBuilder.AppendLine("        {");
            foreach (var target in targets)
                if (IsWritablePropertyForInitializer(target.Symbol))
                    sourceBuilder.AppendLine($"            {target.Name} = read_{target.Name},");

            sourceBuilder.AppendLine("        };");
        }

        sourceBuilder.AppendLine("        return packet;");
        sourceBuilder.AppendLine("    }");

        sourceBuilder.AppendLine("}");

        context.AddSource($"{typeName}.g.cs", SourceText.From(sourceBuilder.ToString(), Encoding.UTF8));
    }

    private static bool HasIgnoreAttribute(ISymbol symbol)
    {
        return symbol.GetAttributes().Any(a =>
            a.AttributeClass?.ToDisplayString() == "System.Text.Json.Serialization.JsonIgnoreAttribute" ||
            a.AttributeClass?.ToDisplayString() == "System.Runtime.Serialization.IgnoreDataMemberAttribute");
    }

    private static bool HasIncludeAttribute(ISymbol symbol)
    {
        return symbol.GetAttributes().Any(a =>
            a.AttributeClass?.ToDisplayString() == "System.Runtime.Serialization.DataMemberAttribute");
    }

    private static List<SerializationTarget> GetSerializationTargets(ITypeSymbol typeSymbol)
    {
        var targets = new List<SerializationTarget>();

        foreach (var currentType in GetSerializableTypeHierarchy(typeSymbol))
        foreach (var member in currentType.GetMembers())
        {
            if (member.IsStatic) continue;
            if (!IsAccessibleFromGeneratedType(member, typeSymbol)) continue;

            if (member is IPropertySymbol p)
            {
                var isPublic = p.DeclaredAccessibility == Accessibility.Public;
                var hasInclude = HasIncludeAttribute(p);
                var hasIgnore = HasIgnoreAttribute(p);

                if ((isPublic && !hasIgnore) || (!isPublic && hasInclude))
                    AddOrReplaceTarget(targets, new SerializationTarget(p.Name, p.Type, p, GetBitFieldKey(p)));
            }
            else if (member is IFieldSymbol f && !f.IsImplicitlyDeclared)
            {
                var hasInclude = HasIncludeAttribute(f);
                if (hasInclude) AddOrReplaceTarget(targets, new SerializationTarget(f.Name, f.Type, f, GetBitFieldKey(f)));
            }
        }

        return targets.Any(t => t.FieldKey.HasValue)
            ? targets.OrderBy(t => t.FieldKey.GetValueOrDefault()).ToList()
            : targets;
    }

    private static IEnumerable<INamedTypeSymbol> GetSerializableTypeHierarchy(ITypeSymbol typeSymbol)
    {
        var stack = new Stack<INamedTypeSymbol>();
        var current = typeSymbol as INamedTypeSymbol;
        while (current != null && current.SpecialType != SpecialType.System_Object)
        {
            stack.Push(current);
            current = current.BaseType;
        }

        return stack;
    }

    private static bool IsAccessibleFromGeneratedType(ISymbol member, ITypeSymbol generatedType)
    {
        if (SymbolEqualityComparer.Default.Equals(member.ContainingType, generatedType)) return true;

        return member.DeclaredAccessibility != Accessibility.Private;
    }

    private static void AddOrReplaceTarget(List<SerializationTarget> targets, SerializationTarget target)
    {
        targets.RemoveAll(t => t.Name == target.Name);
        targets.Add(target);
    }

    private static int? GetBitFieldKey(ISymbol symbol)
    {
        var attr = symbol.GetAttributes()
            .FirstOrDefault(a => a.AttributeClass?.ToDisplayString() == "BitPack.BitFieldKeyAttribute");
        if (attr != null && attr.ConstructorArguments.Length > 0 && attr.ConstructorArguments[0].Value is int key)
            return key;

        return null;
    }

    private static void ValidateTargetSafety(SourceProductionContext context, ITypeSymbol typeSymbol,
        List<SerializationTarget> targets)
    {
        var namedType = typeSymbol as INamedTypeSymbol;

        foreach (var target in targets)
            if (target.Symbol is IPropertySymbol p)
            {
                // 1. Check getter accessor
                if (p.GetMethod == null)
                    context.ReportDiagnostic(Diagnostic.Create(
                        UnsupportedTypeError,
                        p.Locations.FirstOrDefault(),
                        p.Name,
                        $"Property '{p.Name}' must have a getter accessor to be serialized."));

                // 2. Check setter/init or constructor match
                if (p.SetMethod == null)
                {
                    var hasMatchingCtorParam = false;
                    if (namedType != null)
                        foreach (var ctor in namedType.InstanceConstructors)
                            if (ctor.Parameters.Any(param =>
                                    string.Equals(param.Name, p.Name, StringComparison.OrdinalIgnoreCase)))
                            {
                                hasMatchingCtorParam = true;
                                break;
                            }

                    if (!hasMatchingCtorParam)
                        context.ReportDiagnostic(Diagnostic.Create(
                            UnsupportedTypeError,
                            p.Locations.FirstOrDefault(),
                            p.Name,
                        $"Property '{p.Name}' must have a setter or init accessor, or match a constructor parameter to be deserialized."));
                }
            }

        foreach (var target in targets) ValidateMathCodecSafety(context, target);

        var hasAnyFieldKey = targets.Any(t => t.FieldKey.HasValue);
        if (!hasAnyFieldKey) return;

        foreach (var target in targets)
        {
            if (!target.FieldKey.HasValue)
                context.ReportDiagnostic(Diagnostic.Create(
                    BitFieldKeyError,
                    target.Symbol.Locations.FirstOrDefault(),
                    target.Name,
                    "all serializable members must declare [BitFieldKey] when any member declares one."));
            else if (target.FieldKey.Value < 0)
                context.ReportDiagnostic(Diagnostic.Create(
                    BitFieldKeyError,
                    target.Symbol.Locations.FirstOrDefault(),
                    target.Name,
                    "keys must be zero or greater."));
        }

        foreach (var duplicateGroup in targets
                     .Where(t => t.FieldKey.HasValue)
                     .GroupBy(t => t.FieldKey!.Value)
                     .Where(g => g.Count() > 1))
        {
            foreach (var target in duplicateGroup)
                context.ReportDiagnostic(Diagnostic.Create(
                    BitFieldKeyError,
                    target.Symbol.Locations.FirstOrDefault(),
                    target.Name,
                $"key {duplicateGroup.Key} is already used by another serializable member."));
        }
    }

    private static void ValidateMathCodecSafety(SourceProductionContext context, SerializationTarget target)
    {
        var codecCount = 0;
        if (HasAngleAttribute(target.Symbol)) codecCount++;
        if (HasVectorRangeAttribute(target.Symbol)) codecCount++;
        if (HasQuaternionSmallestThreeAttribute(target.Symbol)) codecCount++;

        if (codecCount == 0) return;
        if (codecCount > 1)
        {
            ReportMathCodecError(context, target, "only one game math codec attribute can be applied to a member.");
            return;
        }

        var effectiveType = target.Type is IArrayTypeSymbol arrayType ? arrayType.ElementType : target.Type;

        if (HasAngleAttribute(target.Symbol) &&
            !TryGetAngleConfig(effectiveType, target.Symbol, out _, out var angleError))
            ReportMathCodecError(context, target, angleError);

        if (HasVectorRangeAttribute(target.Symbol) &&
            !TryGetVectorRangeConfig(effectiveType, target.Symbol, out _, out var vectorError))
            ReportMathCodecError(context, target, vectorError);

        if (HasQuaternionSmallestThreeAttribute(target.Symbol) &&
            !TryGetQuaternionSmallestThreeConfig(effectiveType, target.Symbol, out _, out var quaternionError))
            ReportMathCodecError(context, target, quaternionError);
    }

    private static void ReportMathCodecError(SourceProductionContext context, SerializationTarget target, string message)
    {
        context.ReportDiagnostic(Diagnostic.Create(
            MathCodecError,
            target.Symbol.Locations.FirstOrDefault(),
            target.Name,
            message));
    }

    private static IMethodSymbol? FindMatchingConstructor(INamedTypeSymbol? typeSymbol,
        List<SerializationTarget> targets, out List<SerializationTarget> ctorArgs)
    {
        ctorArgs = new List<SerializationTarget>();
        if (typeSymbol == null) return null;
        var ctors = typeSymbol.InstanceConstructors
            .Where(c => c.DeclaredAccessibility == Accessibility.Public ||
                        c.DeclaredAccessibility == Accessibility.Internal)
            .OrderByDescending(c => c.Parameters.Length);

        foreach (var ctor in ctors)
        {
            if (ctor.Parameters.Length == 0) continue;

            var matchedArgs = new List<SerializationTarget>();
            var allMatched = true;

            foreach (var param in ctor.Parameters)
            {
                var target = targets.FirstOrDefault(t =>
                    string.Equals(t.Name, param.Name, StringComparison.OrdinalIgnoreCase));
                if (target != null)
                {
                    matchedArgs.Add(target);
                }
                else
                {
                    allMatched = false;
                    break;
                }
            }

            if (allMatched)
            {
                ctorArgs = matchedArgs;
                return ctor;
            }
        }

        return null;
    }

    private static bool IsWritableProperty(ISymbol symbol)
    {
        if (symbol is IFieldSymbol) return true;
        if (symbol is IPropertySymbol p) return p.SetMethod != null && !p.SetMethod.IsInitOnly;

        return false;
    }

    private static bool IsWritablePropertyForInitializer(ISymbol symbol)
    {
        if (symbol is IFieldSymbol) return true;
        if (symbol is IPropertySymbol p) return p.SetMethod != null;

        return false;
    }

    private static void GenerateSerializationLoop(SourceProductionContext context, StringBuilder sb,
        ITypeSymbol typeSymbol, List<SerializationTarget> targets, bool isWriting, int packetMaxVersion,
        bool skipValidation)
    {
        foreach (var target in targets)
        {
            var propVersion = GetPropertyVersion(target.Symbol);
            if (propVersion > packetMaxVersion)
                context.ReportDiagnostic(Diagnostic.Create(
                    UnsupportedTypeError,
                    target.Symbol.Locations.FirstOrDefault(),
                    target.Name,
                    $"Property version {propVersion} exceeds packet version {packetMaxVersion}."));

            var propSb = new StringBuilder();

            if (isWriting)
            {
                GeneratePropertySerialization(context, propSb, target, true, $"this.{target.Name}", skipValidation);
            }
            else
            {
                if (IsWritableProperty(target.Symbol))
                {
                    GeneratePropertySerialization(context, propSb, target, false, $"this.{target.Name}");
                }
                else
                {
                    propSb.AppendLine(
                        $"        // Read and discard init-only / read-only property '{target.Name}' during instance Deserialize");
                    propSb.AppendLine($"        {target.Type.ToDisplayString()} discard_{target.Name};");
                    GeneratePropertySerialization(context, propSb, target, false, $"discard_{target.Name}");
                }
            }

            if (!isWriting && propVersion > 1)
            {
                sb.AppendLine($"        if (packetVersion >= {propVersion})");
                sb.AppendLine("        {");
                var lines = propSb.ToString().Split(new[] { "\r\n", "\n" }, StringSplitOptions.None);
                foreach (var line in lines)
                    if (!string.IsNullOrWhiteSpace(line))
                        sb.AppendLine("    " + line);

                sb.AppendLine("        }");
            }
            else
            {
                sb.Append(propSb);
            }
        }
    }

    private static void GeneratePropertySerialization(SourceProductionContext context, StringBuilder sb,
        SerializationTarget target, bool isWriting, string targetVarName, bool skipValidation = false)
    {
        var propType = target.Type;

        if (propType is IArrayTypeSymbol arrayType)
        {
            GenerateArraySerialization(context, sb, target, arrayType, isWriting, targetVarName, skipValidation);
            return;
        }

        if (TryGetAngleConfig(propType, target.Symbol, out var angleConfig, out _))
        {
            GenerateAngleSerialization(sb, propType, target, angleConfig, isWriting, targetVarName, skipValidation);
            return;
        }

        if (TryGetVectorRangeConfig(propType, target.Symbol, out var vectorConfig, out _))
        {
            GenerateVectorRangeSerialization(sb, propType, target, vectorConfig, isWriting, targetVarName, skipValidation);
            return;
        }

        if (TryGetQuaternionSmallestThreeConfig(propType, target.Symbol, out var quaternionConfig, out _))
        {
            GenerateQuaternionSmallestThreeSerialization(sb, target, quaternionConfig, isWriting, targetVarName, skipValidation);
            return;
        }

        // Check for custom serialization or bit packet nested properties
        var isBitPacket = IsBitPacketType(propType);
        var hasCustom = ExposesCustomSerialization(propType, out var staticMethodName);

        // 1. Boolean
        if (propType.SpecialType == SpecialType.System_Boolean)
        {
            if (isWriting)
                sb.AppendLine($"        writer.WriteBool({targetVarName});");
            else
                sb.AppendLine($"        {targetVarName} = reader.ReadBool();");
        }
        // 2. Char
        else if (propType.SpecialType == SpecialType.System_Char)
        {
            if (isWriting)
                sb.AppendLine($"        writer.WriteInt((int){targetVarName}, 16);");
            else
                sb.AppendLine($"        {targetVarName} = (char)reader.ReadInt(16);");
        }
        // 3. String
        else if (propType.SpecialType == SpecialType.System_String)
        {
            var maxLen = GetMaxLen(target.Symbol, out var hasConstraint);
            if (!hasConstraint && isWriting && !skipValidation) ReportWarning(context, target.Symbol);

            if (isWriting)
                sb.AppendLine(
                    $"        writer.WriteString({targetVarName}, {maxLen}, {CalculateBitsNeeded(maxLen * 4)});");
            else
                sb.AppendLine(
                    $"        {targetVarName} = reader.ReadString({maxLen}, {CalculateBitsNeeded(maxLen * 4)});");
        }
        // 4. DateTime
        else if (propType.ToDisplayString() == "System.DateTime")
        {
            if (isWriting)
                sb.AppendLine($"        writer.WriteDateTime({targetVarName});");
            else
                sb.AppendLine($"        {targetVarName} = reader.ReadDateTime();");
        }
        // 5. Enum
        else if (propType.TypeKind == TypeKind.Enum)
        {
            var bits = GetEnumBits(propType, target.Symbol);
            if (isWriting)
            {
                // Extract range for bounds checking
                long enumMin = 0, enumMax = 0;
                var rangeAttr = target.Symbol.GetAttributes()
                    .FirstOrDefault(a =>
                        a.AttributeClass?.ToDisplayString() == "System.ComponentModel.DataAnnotations.RangeAttribute");
                if (rangeAttr != null && rangeAttr.ConstructorArguments.Length >= 2)
                {
                    try
                    {
                        enumMin = Convert.ToInt64(rangeAttr.ConstructorArguments[0].Value);
                    }
                    catch
                    {
                    }

                    try
                    {
                        enumMax = Convert.ToInt64(rangeAttr.ConstructorArguments[1].Value);
                    }
                    catch
                    {
                    }
                }
                else
                {
                    foreach (var field in propType.GetMembers().OfType<IFieldSymbol>())
                        if (field.HasConstantValue)
                        {
                            var val = Convert.ToInt64(field.ConstantValue);
                            if (val > enumMax) enumMax = val;
                            if (val < enumMin) enumMin = val;
                        }
                }

                if (!skipValidation)
                    sb.AppendLine(
                        $"        if ((int){targetVarName} < {enumMin} || (int){targetVarName} > {enumMax}) throw new ArgumentOutOfRangeException(nameof({targetVarName}), (object){targetVarName}, $\"Enum value must be within [{enumMin}, {enumMax}].\");");
                sb.AppendLine($"        writer.WriteInt((int){targetVarName}, {bits});");
            }
            else
            {
                var enumFields = propType.GetMembers().OfType<IFieldSymbol>().Where(f => f.HasConstantValue).ToList();
                var enumTypeName = propType.ToDisplayString();
                long maxVal = 0;
                long defaultVal = 0;
                var hasZero = false;
                foreach (var field in enumFields)
                {
                    var val = Convert.ToInt64(field.ConstantValue);
                    if (val > maxVal) maxVal = val;
                    if (val == 0) hasZero = true;
                }

                if (!hasZero && enumFields.Count > 0)
                    defaultVal = Convert.ToInt64(enumFields[0].ConstantValue);
                sb.AppendLine($"        var temp{target.Name} = reader.ReadInt({bits});");
                sb.AppendLine(
                    $"        {targetVarName} = temp{target.Name} <= {maxVal} ? ({enumTypeName})temp{target.Name} : ({enumTypeName}){defaultVal};");
            }
        }
        // 6. Floating-point (float, double) with fixed-point quantization
        else if (propType.SpecialType is SpecialType.System_Single or SpecialType.System_Double)
        {
            var isQuantized = GetQuantizationConfig(target.Symbol, out var minVal, out var maxVal, out var decimals,
                out var scale, out var bits);

            if (isQuantized)
            {
                var castStr = propType.SpecialType == SpecialType.System_Single ? "float" : "double";
                if (isWriting)
                {
                    if (!skipValidation)
                        sb.AppendLine(
                            $"        if ({targetVarName} < {minVal} || {targetVarName} > {maxVal}) throw new ArgumentOutOfRangeException(nameof({targetVarName}), {targetVarName}, $\"Value must be within [{minVal}, {maxVal}].\");");
                    sb.AppendLine(
                        $"        writer.WriteLong((long)(({targetVarName} - ({minVal})) * {scale}d + 0.5d), {bits});");
                }
                else
                {
                    sb.AppendLine(
                        $"        {targetVarName} = ({castStr})((double)reader.ReadLong({bits}) / {scale}d + ({minVal}));");
                }
            }
            else
            {
                // Fall back to full float/double representation
                if (isWriting)
                {
                    if (!skipValidation) ReportWarning(context, target.Symbol);
                    if (propType.SpecialType == SpecialType.System_Single)
                        sb.AppendLine($"        writer.WriteFloat({targetVarName});");
                    else
                        sb.AppendLine($"        writer.WriteDouble({targetVarName});");
                }
                else
                {
                    if (propType.SpecialType == SpecialType.System_Single)
                        sb.AppendLine($"        {targetVarName} = reader.ReadFloat();");
                    else
                        sb.AppendLine($"        {targetVarName} = reader.ReadDouble();");
                }
            }
        }
        // 6.5. Decimal
        else if (propType.SpecialType == SpecialType.System_Decimal)
        {
            if (isWriting)
                sb.AppendLine($"        writer.WriteDecimal({targetVarName});");
            else
                sb.AppendLine($"        {targetVarName} = reader.ReadDecimal();");
        }
        // 6.6. Native integers (nint, nuint, IntPtr, UIntPtr)
        else if (propType.ToDisplayString() == "nint" || propType.ToDisplayString() == "System.IntPtr")
        {
            var bits = GetNumericBits(propType, target.Symbol, out var hasConstraint, out var minVal, out var maxVal);
            if (isWriting)
            {
                if (hasConstraint)
                {
                    if (!skipValidation)
                        sb.AppendLine(
                            $"        if ({targetVarName} < {minVal} || {targetVarName} > {maxVal}) throw new ArgumentOutOfRangeException(nameof({targetVarName}), {targetVarName}, $\"Value must be within [{minVal}, {maxVal}].\");");
                    sb.AppendLine($"        writer.WriteLong((long)({targetVarName} - ({minVal})), {bits});");
                }
                else
                {
                    sb.AppendLine($"        writer.WriteLong((long){targetVarName}, {bits});");
                }
            }
            else
            {
                if (hasConstraint)
                    sb.AppendLine($"        {targetVarName} = (nint)(reader.ReadLong({bits}) + ({minVal}));");
                else
                    sb.AppendLine($"        {targetVarName} = (nint)reader.ReadLong({bits});");
            }
        }
        else if (propType.ToDisplayString() == "nuint" || propType.ToDisplayString() == "System.UIntPtr")
        {
            var bits = GetNumericBits(propType, target.Symbol, out var hasConstraint, out var minVal, out var maxVal);
            if (isWriting)
            {
                if (hasConstraint)
                {
                    if (!skipValidation)
                        sb.AppendLine(
                            $"        if ({targetVarName} < {minVal} || {targetVarName} > {maxVal}) throw new ArgumentOutOfRangeException(nameof({targetVarName}), {targetVarName}, $\"Value must be within [{minVal}, {maxVal}].\");");
                    sb.AppendLine($"        writer.WriteULong((ulong)({targetVarName} - ({minVal})), {bits});");
                }
                else
                {
                    sb.AppendLine($"        writer.WriteULong((ulong){targetVarName}, {bits});");
                }
            }
            else
            {
                if (hasConstraint)
                    sb.AppendLine($"        {targetVarName} = (nuint)(reader.ReadULong({bits}) + ({minVal}));");
                else
                    sb.AppendLine($"        {targetVarName} = (nuint)reader.ReadULong({bits});");
            }
        }
        // 6.7. Interface Types
        else if (propType.TypeKind == TypeKind.Interface)
        {
            var implementsBitSerializable =
                propType.AllInterfaces.Any(i => i.ToDisplayString() == "BitPack.IBitSerializable") ||
                propType.ToDisplayString() == "BitPack.IBitSerializable";
            if (implementsBitSerializable)
            {
                if (isWriting)
                    sb.AppendLine($"        {targetVarName}.Serialize(writer);");
                else
                    sb.AppendLine($"        {targetVarName}.Deserialize(reader);");
            }
            else
            {
                if (isWriting && !skipValidation)
                    ReportError(context, target.Symbol);
                sb.AppendLine(
                    $"        // ERROR: Interface property '{targetVarName}' of type '{propType.ToDisplayString()}' must implement IBitSerializable.");
            }
        }
        // 7. Nested Packets or Custom Value Objects
        else if (isBitPacket || hasCustom)
        {
            if (isWriting)
            {
                sb.AppendLine($"        {targetVarName}.Serialize(writer);");
            }
            else
            {
                if (isBitPacket)
                {
                    sb.AppendLine($"        {targetVarName} = {propType.ToDisplayString()}.Read(reader);");
                }
                else if (staticMethodName != null)
                {
                    sb.AppendLine(
                        $"        {targetVarName} = {propType.ToDisplayString()}.{staticMethodName}(reader);");
                }
                else
                {
                    sb.AppendLine($"        {targetVarName} = new {propType.ToDisplayString()}();");
                    sb.AppendLine($"        {targetVarName}.Deserialize(reader);");
                }
            }
        }
        // 8. Unsigned integers (uint, ulong)
        else if (propType.SpecialType is SpecialType.System_UInt32 or SpecialType.System_UInt64)
        {
            var bits = GetNumericBits(propType, target.Symbol, out var hasConstraint, out var minVal, out var maxVal);
            if (!hasConstraint && isWriting && !skipValidation) ReportWarning(context, target.Symbol);

            if (isWriting)
            {
                if (hasConstraint)
                {
                    if (!skipValidation)
                        sb.AppendLine(
                            $"        if ({targetVarName} < {minVal} || {targetVarName} > {maxVal}) throw new ArgumentOutOfRangeException(nameof({targetVarName}), {targetVarName}, $\"Value must be within [{minVal}, {maxVal}].\");");
                    sb.AppendLine($"        writer.WriteULong((ulong)({targetVarName} - ({minVal})), {bits});");
                }
                else
                {
                    sb.AppendLine($"        writer.WriteULong((ulong){targetVarName}, {bits});");
                }
            }
            else
            {
                if (hasConstraint)
                    sb.AppendLine(
                        $"        {targetVarName} = ({propType.ToDisplayString()})(reader.ReadULong({bits}) + ({minVal}));");
                else
                    sb.AppendLine($"        {targetVarName} = ({propType.ToDisplayString()})reader.ReadULong({bits});");
            }
        }
        // 9. Signed or small integers (sbyte, byte, short, ushort, int, long)
        else if (propType.SpecialType is SpecialType.System_SByte or SpecialType.System_Byte or SpecialType.System_Int16
                 or SpecialType.System_UInt16 or SpecialType.System_Int32 or SpecialType.System_Int64)
        {
            var bits = GetNumericBits(propType, target.Symbol, out var hasConstraint, out var minVal, out var maxVal);
            if (!hasConstraint && isWriting && !skipValidation) ReportWarning(context, target.Symbol);

            if (isWriting)
            {
                if (hasConstraint)
                {
                    if (!skipValidation)
                        sb.AppendLine(
                            $"        if ({targetVarName} < {minVal} || {targetVarName} > {maxVal}) throw new ArgumentOutOfRangeException(nameof({targetVarName}), {targetVarName}, $\"Value must be within [{minVal}, {maxVal}].\");");
                    sb.AppendLine($"        writer.WriteLong((long)({targetVarName} - ({minVal})), {bits});");
                }
                else
                {
                    sb.AppendLine($"        writer.WriteLong((long){targetVarName}, {bits});");
                }
            }
            else
            {
                if (hasConstraint)
                    sb.AppendLine(
                        $"        {targetVarName} = ({propType.ToDisplayString()})(reader.ReadLong({bits}) + ({minVal}));");
                else
                    sb.AppendLine($"        {targetVarName} = ({propType.ToDisplayString()})reader.ReadLong({bits});");
            }
        }
        // 10. Unsupported complex structures (raise build-time Error BP0001)
        else
        {
            if (isWriting && !skipValidation) ReportError(context, target.Symbol);

            sb.AppendLine(
                $"        // ERROR: Property '{targetVarName}' of type '{propType.ToDisplayString()}' is not packable.");
        }
    }

    private static void GenerateAngleSerialization(StringBuilder sb, ITypeSymbol propType, SerializationTarget target,
        AngleConfig config, bool isWriting, string targetVarName, bool skipValidation)
    {
        var suffix = SanitizeIdentifier(target.Name);
        var scale = 1L << config.Bits;
        var maxEncoded = scale - 1;
        var cast = propType.SpecialType == SpecialType.System_Single ? "float" : "double";

        if (isWriting)
        {
            if (!skipValidation)
                sb.AppendLine(
                    $"        if ({targetVarName} < 0d || {targetVarName} >= 360d) throw new ArgumentOutOfRangeException(nameof({targetVarName}), {targetVarName}, \"Angle must be in the range [0, 360).\");");
            sb.AppendLine(
                $"        var encodedAngle_{suffix} = (long)Math.Floor(((double){targetVarName} * {scale}d / 360d) + 0.5d);");
            sb.AppendLine($"        if (encodedAngle_{suffix} > {maxEncoded}L) encodedAngle_{suffix} = {maxEncoded}L;");
            sb.AppendLine($"        writer.WriteLong(encodedAngle_{suffix}, {config.Bits});");
        }
        else
        {
            sb.AppendLine($"        {targetVarName} = ({cast})((double)reader.ReadLong({config.Bits}) * 360d / {scale}d);");
        }
    }

    private static void GenerateVectorRangeSerialization(StringBuilder sb, ITypeSymbol propType,
        SerializationTarget target, VectorRangeConfig config, bool isWriting, string targetVarName, bool skipValidation)
    {
        var suffix = SanitizeIdentifier(target.Name);
        var isVector3 = propType.ToDisplayString() == "System.Numerics.Vector3";

        if (isWriting)
        {
            GenerateVectorComponentWrite(sb, targetVarName, "X", suffix, config, skipValidation);
            GenerateVectorComponentWrite(sb, targetVarName, "Y", suffix, config, skipValidation);
            if (isVector3) GenerateVectorComponentWrite(sb, targetVarName, "Z", suffix, config, skipValidation);
        }
        else
        {
            GenerateVectorComponentRead(sb, "X", suffix, config);
            GenerateVectorComponentRead(sb, "Y", suffix, config);
            if (isVector3) GenerateVectorComponentRead(sb, "Z", suffix, config);
            sb.AppendLine(isVector3
                ? $"        {targetVarName} = new System.Numerics.Vector3((float)decoded_{suffix}_X, (float)decoded_{suffix}_Y, (float)decoded_{suffix}_Z);"
                : $"        {targetVarName} = new System.Numerics.Vector2((float)decoded_{suffix}_X, (float)decoded_{suffix}_Y);");
        }
    }

    private static void GenerateVectorComponentWrite(StringBuilder sb, string targetVarName, string component,
        string suffix, VectorRangeConfig config, bool skipValidation)
    {
        var componentAccess = $"{targetVarName}.{component}";
        if (!skipValidation)
            sb.AppendLine(
                $"        if ({componentAccess} < {config.Min}d || {componentAccess} > {config.Max}d) throw new ArgumentOutOfRangeException(nameof({targetVarName}), {componentAccess}, \"Vector component must be within [{config.Min}, {config.Max}].\");");
        sb.AppendLine(
            $"        writer.WriteLong((long)(((double){componentAccess} - ({config.Min}d)) * {config.Scale}d + 0.5d), {config.Bits});");
    }

    private static void GenerateVectorComponentRead(StringBuilder sb, string component, string suffix,
        VectorRangeConfig config)
    {
        sb.AppendLine(
            $"        var decoded_{suffix}_{component} = (double)reader.ReadLong({config.Bits}) / {config.Scale}d + ({config.Min}d);");
    }

    private static void GenerateQuaternionSmallestThreeSerialization(StringBuilder sb, SerializationTarget target,
        QuaternionSmallestThreeConfig config, bool isWriting, string targetVarName, bool skipValidation)
    {
        var suffix = SanitizeIdentifier(target.Name);
        var maxEncoded = (1L << config.BitsPerComponent) - 1;
        const string limit = "0.7071067811865476d";

        if (isWriting)
        {
            sb.AppendLine($"        var q_{suffix} = {targetVarName};");
            sb.AppendLine(
                $"        var lenSq_{suffix} = (double)q_{suffix}.X * q_{suffix}.X + (double)q_{suffix}.Y * q_{suffix}.Y + (double)q_{suffix}.Z * q_{suffix}.Z + (double)q_{suffix}.W * q_{suffix}.W;");
            sb.AppendLine(
                $"        if (lenSq_{suffix} <= 0d) throw new ArgumentOutOfRangeException(nameof({targetVarName}), {targetVarName}, \"Quaternion length must be greater than zero.\");");
            sb.AppendLine($"        var invLen_{suffix} = 1d / Math.Sqrt(lenSq_{suffix});");
            sb.AppendLine($"        var qx_{suffix} = q_{suffix}.X * invLen_{suffix};");
            sb.AppendLine($"        var qy_{suffix} = q_{suffix}.Y * invLen_{suffix};");
            sb.AppendLine($"        var qz_{suffix} = q_{suffix}.Z * invLen_{suffix};");
            sb.AppendLine($"        var qw_{suffix} = q_{suffix}.W * invLen_{suffix};");
            sb.AppendLine($"        var largestIndex_{suffix} = 0;");
            sb.AppendLine($"        var largestAbs_{suffix} = Math.Abs(qx_{suffix});");
            sb.AppendLine($"        if (Math.Abs(qy_{suffix}) > largestAbs_{suffix}) {{ largestIndex_{suffix} = 1; largestAbs_{suffix} = Math.Abs(qy_{suffix}); }}");
            sb.AppendLine($"        if (Math.Abs(qz_{suffix}) > largestAbs_{suffix}) {{ largestIndex_{suffix} = 2; largestAbs_{suffix} = Math.Abs(qz_{suffix}); }}");
            sb.AppendLine($"        if (Math.Abs(qw_{suffix}) > largestAbs_{suffix}) largestIndex_{suffix} = 3;");
            sb.AppendLine($"        var largestValue_{suffix} = largestIndex_{suffix} == 0 ? qx_{suffix} : largestIndex_{suffix} == 1 ? qy_{suffix} : largestIndex_{suffix} == 2 ? qz_{suffix} : qw_{suffix};");
            sb.AppendLine($"        if (largestValue_{suffix} < 0d) {{ qx_{suffix} = -qx_{suffix}; qy_{suffix} = -qy_{suffix}; qz_{suffix} = -qz_{suffix}; qw_{suffix} = -qw_{suffix}; }}");
            sb.AppendLine($"        writer.WriteInt(largestIndex_{suffix}, 2);");
            GenerateQuaternionComponentWrite(sb, "x", suffix, config, maxEncoded, limit);
            GenerateQuaternionComponentWrite(sb, "y", suffix, config, maxEncoded, limit);
            GenerateQuaternionComponentWrite(sb, "z", suffix, config, maxEncoded, limit);
            GenerateQuaternionComponentWrite(sb, "w", suffix, config, maxEncoded, limit);
        }
        else
        {
            sb.AppendLine($"        var largestIndex_{suffix} = reader.ReadInt(2);");
            sb.AppendLine($"        var qx_{suffix} = 0d;");
            sb.AppendLine($"        var qy_{suffix} = 0d;");
            sb.AppendLine($"        var qz_{suffix} = 0d;");
            sb.AppendLine($"        var qw_{suffix} = 0d;");
            GenerateQuaternionComponentRead(sb, "x", suffix, config, maxEncoded, limit);
            GenerateQuaternionComponentRead(sb, "y", suffix, config, maxEncoded, limit);
            GenerateQuaternionComponentRead(sb, "z", suffix, config, maxEncoded, limit);
            GenerateQuaternionComponentRead(sb, "w", suffix, config, maxEncoded, limit);
            sb.AppendLine($"        var omitted_{suffix} = Math.Sqrt(Math.Max(0d, 1d - (qx_{suffix} * qx_{suffix} + qy_{suffix} * qy_{suffix} + qz_{suffix} * qz_{suffix} + qw_{suffix} * qw_{suffix})));");
            sb.AppendLine($"        if (largestIndex_{suffix} == 0) qx_{suffix} = omitted_{suffix};");
            sb.AppendLine($"        else if (largestIndex_{suffix} == 1) qy_{suffix} = omitted_{suffix};");
            sb.AppendLine($"        else if (largestIndex_{suffix} == 2) qz_{suffix} = omitted_{suffix};");
            sb.AppendLine($"        else qw_{suffix} = omitted_{suffix};");
            sb.AppendLine($"        {targetVarName} = new System.Numerics.Quaternion((float)qx_{suffix}, (float)qy_{suffix}, (float)qz_{suffix}, (float)qw_{suffix});");
        }
    }

    private static void GenerateQuaternionComponentWrite(StringBuilder sb, string component, string suffix,
        QuaternionSmallestThreeConfig config, long maxEncoded, string limit)
    {
        var index = component == "x" ? 0 : component == "y" ? 1 : component == "z" ? 2 : 3;
        sb.AppendLine($"        if (largestIndex_{suffix} != {index})");
        sb.AppendLine("        {");
        sb.AppendLine($"        var encodedQ_{suffix}_{component} = (long)((((q{component}_{suffix} + {limit}) / (2d * {limit})) * {maxEncoded}d) + 0.5d);");
        sb.AppendLine($"        if (encodedQ_{suffix}_{component} < 0L) encodedQ_{suffix}_{component} = 0L;");
        sb.AppendLine($"        else if (encodedQ_{suffix}_{component} > {maxEncoded}L) encodedQ_{suffix}_{component} = {maxEncoded}L;");
        sb.AppendLine($"        writer.WriteLong(encodedQ_{suffix}_{component}, {config.BitsPerComponent});");
        sb.AppendLine("        }");
    }

    private static void GenerateQuaternionComponentRead(StringBuilder sb, string component, string suffix,
        QuaternionSmallestThreeConfig config, long maxEncoded, string limit)
    {
        var index = component == "x" ? 0 : component == "y" ? 1 : component == "z" ? 2 : 3;
        sb.AppendLine($"        if (largestIndex_{suffix} != {index}) q{component}_{suffix} = (double)reader.ReadLong({config.BitsPerComponent}) / {maxEncoded}d * (2d * {limit}) - {limit};");
    }

    private static void GenerateArraySerialization(SourceProductionContext context, StringBuilder sb,
        SerializationTarget target, IArrayTypeSymbol arrayType, bool isWriting, string targetVarName,
        bool skipValidation)
    {
        if (!TryGetArrayConfig(target.Symbol, arrayType, out var config, out var error))
        {
            if (isWriting && !skipValidation)
                context.ReportDiagnostic(Diagnostic.Create(
                    BoundedArrayError,
                    target.Symbol.Locations.FirstOrDefault(),
                    target.Name,
                    error));

            sb.AppendLine(
                $"        // ERROR: Array property '{targetVarName}' of type '{arrayType.ToDisplayString()}' must be a supported bounded array.");
            return;
        }

        var elementTypeName = arrayType.ElementType.ToDisplayString();
        var elementTarget = new SerializationTarget($"{target.Name}Element", arrayType.ElementType, target.Symbol, null);

        if (isWriting)
        {
            var valueVar = $"value_{SanitizeIdentifier(target.Name)}";
            var indexVar = $"i_{SanitizeIdentifier(target.Name)}";
            var elementVar = $"element_{SanitizeIdentifier(target.Name)}";
            if (config.IsFixed)
            {
                sb.AppendLine(
                    $"        if ({targetVarName} == null || {targetVarName}.Length != {config.Count}) throw new ArgumentOutOfRangeException(nameof({targetVarName}), {targetVarName}?.Length, \"Array length must be exactly {config.Count}.\");");
                sb.AppendLine($"        for (var {indexVar} = 0; {indexVar} < {config.Count}; {indexVar}++)");
                sb.AppendLine("        {");
                sb.AppendLine($"        var {elementVar} = {targetVarName}[{indexVar}];");
                GeneratePropertySerialization(context, sb, elementTarget, true, elementVar, skipValidation);
                sb.AppendLine("        }");
            }
            else
            {
                sb.AppendLine($"        var {valueVar} = {targetVarName} ?? Array.Empty<{elementTypeName}>();");
                sb.AppendLine(
                    $"        if ({valueVar}.Length > {config.Count}) throw new ArgumentOutOfRangeException(nameof({targetVarName}), {valueVar}.Length, \"Array length must be less than or equal to {config.Count}.\");");
                sb.AppendLine($"        writer.WriteInt({valueVar}.Length, {config.LengthBits});");
                sb.AppendLine($"        for (var {indexVar} = 0; {indexVar} < {valueVar}.Length; {indexVar}++)");
                sb.AppendLine("        {");
                sb.AppendLine($"        var {elementVar} = {valueVar}[{indexVar}];");
                GeneratePropertySerialization(context, sb, elementTarget, true, elementVar, skipValidation);
                sb.AppendLine("        }");
            }
        }
        else
        {
            var lengthVar = config.IsFixed ? config.Count.ToString() : $"length_{SanitizeIdentifier(target.Name)}";
            if (!config.IsFixed) sb.AppendLine($"        var {lengthVar} = reader.ReadInt({config.LengthBits});");

            sb.AppendLine($"        {targetVarName} = new {elementTypeName}[{lengthVar}];");
            sb.AppendLine($"        for (var i_{SanitizeIdentifier(target.Name)} = 0; i_{SanitizeIdentifier(target.Name)} < {targetVarName}.Length; i_{SanitizeIdentifier(target.Name)}++)");
            sb.AppendLine("        {");
            GeneratePropertySerialization(context, sb, elementTarget, false,
                $"{targetVarName}[i_{SanitizeIdentifier(target.Name)}]", skipValidation);
            sb.AppendLine("        }");
        }
    }

    private static string SanitizeIdentifier(string value)
    {
        var sb = new StringBuilder(value.Length);
        foreach (var ch in value)
            sb.Append(char.IsLetterOrDigit(ch) || ch == '_' ? ch : '_');

        if (sb.Length == 0 || char.IsDigit(sb[0])) sb.Insert(0, '_');
        return sb.ToString();
    }

    private static bool TryGetArrayConfig(ISymbol symbol, IArrayTypeSymbol arrayType, out ArrayConfig config,
        out string error)
    {
        config = default;
        error = string.Empty;

        if (arrayType.Rank != 1)
        {
            error = "only one-dimensional arrays are supported.";
            return false;
        }

        if (arrayType.ElementType is IArrayTypeSymbol)
        {
            error = "jagged arrays are not supported.";
            return false;
        }

        if (arrayType.ElementType.SpecialType == SpecialType.System_String)
        {
            error = "string arrays are not supported yet because array length and element string length need separate bounds.";
            return false;
        }

        if (arrayType.ElementType.TypeKind == TypeKind.Interface)
        {
            error = "interface arrays are not supported because elements cannot be preallocated during deserialization.";
            return false;
        }

        var hasMaxLength = TryGetMaxLength(symbol, out var maxLength);
        var hasFixedCount = TryGetFixedCount(symbol, out var fixedCount);

        if (hasMaxLength && hasFixedCount)
        {
            error = "use either [MaxLength] or [FixedCount], not both.";
            return false;
        }

        if (!hasMaxLength && !hasFixedCount)
        {
            error = "arrays must declare [MaxLength] or [FixedCount].";
            return false;
        }

        if (hasMaxLength)
        {
            if (maxLength < 0)
            {
                error = "[MaxLength] must be zero or greater.";
                return false;
            }

            config = new ArrayConfig(false, maxLength, CalculateBitsNeeded(maxLength));
            return true;
        }

        if (fixedCount <= 0)
        {
            error = "[FixedCount] must be greater than zero.";
            return false;
        }

        config = new ArrayConfig(true, fixedCount, 0);
        return true;
    }

    private static bool TryGetFixedCount(ISymbol symbol, out int count)
    {
        count = 0;
        var attr = symbol.GetAttributes()
            .FirstOrDefault(a =>
                a.AttributeClass?.ToDisplayString() is "BitPack.FixedCountAttribute" or "BitPack.FixedCount");
        if (attr != null && attr.ConstructorArguments.Length > 0 && attr.ConstructorArguments[0].Value is int value)
        {
            count = value;
            return true;
        }

        return false;
    }

    private static bool HasAngleAttribute(ISymbol symbol)
    {
        return symbol.GetAttributes().Any(a => a.AttributeClass?.ToDisplayString() == "BitPack.AngleAttribute");
    }

    private static bool HasVectorRangeAttribute(ISymbol symbol)
    {
        return symbol.GetAttributes().Any(a => a.AttributeClass?.ToDisplayString() == "BitPack.VectorRangeAttribute");
    }

    private static bool HasQuaternionSmallestThreeAttribute(ISymbol symbol)
    {
        return symbol.GetAttributes()
            .Any(a => a.AttributeClass?.ToDisplayString() == "BitPack.QuaternionSmallestThreeAttribute");
    }

    private static bool TryGetAngleConfig(ITypeSymbol type, ISymbol symbol, out AngleConfig config, out string error)
    {
        config = default;
        error = string.Empty;
        var attr = symbol.GetAttributes()
            .FirstOrDefault(a => a.AttributeClass?.ToDisplayString() == "BitPack.AngleAttribute");
        if (attr == null) return false;

        if (type.SpecialType is not (SpecialType.System_Single or SpecialType.System_Double))
        {
            error = "[Angle] can only be applied to float or double values.";
            return false;
        }

        var bits = attr.ConstructorArguments.Length > 0 && attr.ConstructorArguments[0].Value is int value ? value : 16;
        if (bits is < 1 or > 30)
        {
            error = "[Angle] bits must be between 1 and 30.";
            return false;
        }

        config = new AngleConfig(bits);
        return true;
    }

    private static bool TryGetVectorRangeConfig(ITypeSymbol type, ISymbol symbol, out VectorRangeConfig config,
        out string error)
    {
        config = default;
        error = string.Empty;
        var attr = symbol.GetAttributes()
            .FirstOrDefault(a => a.AttributeClass?.ToDisplayString() == "BitPack.VectorRangeAttribute");
        if (attr == null) return false;

        var typeName = type.ToDisplayString();
        if (typeName is not ("System.Numerics.Vector2" or "System.Numerics.Vector3"))
        {
            error = "[VectorRange] can only be applied to System.Numerics.Vector2 or Vector3 values.";
            return false;
        }

        if (attr.ConstructorArguments.Length < 3 || attr.ConstructorArguments[0].Value == null ||
            attr.ConstructorArguments[1].Value == null || attr.ConstructorArguments[2].Value is not int decimals)
        {
            error = "[VectorRange] requires minimum, maximum, and decimals constructor arguments.";
            return false;
        }

        var min = Convert.ToDouble(attr.ConstructorArguments[0].Value);
        var max = Convert.ToDouble(attr.ConstructorArguments[1].Value);
        if (max <= min)
        {
            error = "[VectorRange] maximum must be greater than minimum.";
            return false;
        }

        if (decimals < 0)
        {
            error = "[VectorRange] decimals must be zero or greater.";
            return false;
        }

        var scale = Math.Pow(10, decimals);
        var rangeSize = (max - min) * scale;
        var bits = CalculateBitsNeeded((int)Math.Ceiling(rangeSize));
        if (bits > 62)
        {
            error = "[VectorRange] requires too many bits per component.";
            return false;
        }

        config = new VectorRangeConfig(min, max, decimals, scale, bits);
        return true;
    }

    private static bool TryGetQuaternionSmallestThreeConfig(ITypeSymbol type, ISymbol symbol,
        out QuaternionSmallestThreeConfig config, out string error)
    {
        config = default;
        error = string.Empty;
        var attr = symbol.GetAttributes()
            .FirstOrDefault(a => a.AttributeClass?.ToDisplayString() == "BitPack.QuaternionSmallestThreeAttribute");
        if (attr == null) return false;

        if (type.ToDisplayString() != "System.Numerics.Quaternion")
        {
            error = "[QuaternionSmallestThree] can only be applied to System.Numerics.Quaternion values.";
            return false;
        }

        var bits = attr.ConstructorArguments.Length > 0 && attr.ConstructorArguments[0].Value is int value ? value : 16;
        if (bits is < 2 or > 30)
        {
            error = "[QuaternionSmallestThree] bits per component must be between 2 and 30.";
            return false;
        }

        config = new QuaternionSmallestThreeConfig(bits);
        return true;
    }

    private static bool TryGetMaxLength(ISymbol symbol, out int maxLength)
    {
        maxLength = 0;
        var attr = symbol.GetAttributes()
            .FirstOrDefault(a =>
                a.AttributeClass?.ToDisplayString() == "System.ComponentModel.DataAnnotations.MaxLengthAttribute");
        if (attr != null && attr.ConstructorArguments.Length > 0 && attr.ConstructorArguments[0].Value is int value)
        {
            maxLength = value;
            return true;
        }

        return false;
    }

    private static bool IsBitPacketType(ITypeSymbol type)
    {
        return type.GetAttributes().Any(a =>
            a.AttributeClass?.ToDisplayString() == "BitPack.BitPacketAttribute");
    }

    private static bool ExposesCustomSerialization(ITypeSymbol type, out string? staticMethodName)
    {
        var members = type.GetMembers();
        var hasSerialize = members.OfType<IMethodSymbol>().Any(m =>
            m.Name == "Serialize" &&
            m.Parameters.Length == 1 &&
            m.Parameters[0].Type.ToDisplayString() == "BitPack.BitWriter");

        var staticDeserializer = members.OfType<IMethodSymbol>().FirstOrDefault(m =>
            m.IsStatic &&
            (m.Name == "Deserialize" || m.Name == "Read") &&
            m.Parameters.Length == 1 &&
            m.Parameters[0].Type.ToDisplayString() == "BitPack.BitReader" &&
            SymbolEqualityComparer.Default.Equals(m.ReturnType, type));

        staticMethodName = staticDeserializer?.Name;
        return hasSerialize;
    }

    private static bool GetQuantizationConfig(ISymbol symbol, out double minVal, out double maxVal, out int decimals,
        out double scale, out int bits)
    {
        minVal = 0;
        maxVal = 0;
        decimals = 0;
        scale = 1;
        bits = 32;

        var rangeAttr = symbol.GetAttributes()
            .FirstOrDefault(a =>
                a.AttributeClass?.ToDisplayString() == "System.ComponentModel.DataAnnotations.RangeAttribute");

        var precisionAttr = symbol.GetAttributes()
            .FirstOrDefault(a => a.AttributeClass?.ToDisplayString() == "BitPack.PrecisionAttribute");

        if (rangeAttr != null && precisionAttr != null && rangeAttr.ConstructorArguments.Length >= 2 &&
            precisionAttr.ConstructorArguments.Length > 0)
            try
            {
                minVal = Convert.ToDouble(rangeAttr.ConstructorArguments[0].Value);
                maxVal = Convert.ToDouble(rangeAttr.ConstructorArguments[1].Value);
                decimals = Convert.ToInt32(precisionAttr.ConstructorArguments[0].Value);

                scale = Math.Pow(10, decimals);
                var rangeSize = (maxVal - minVal) * scale;
                bits = (int)Math.Ceiling(Math.Log(rangeSize + 1, 2));
                return true;
            }
            catch
            {
            }

        return false;
    }

    private static int GetEnumBits(ITypeSymbol enumType, ISymbol symbol)
    {
        var rangeAttr = symbol.GetAttributes()
            .FirstOrDefault(a =>
                a.AttributeClass?.ToDisplayString() == "System.ComponentModel.DataAnnotations.RangeAttribute");

        if (rangeAttr != null && rangeAttr.ConstructorArguments.Length >= 2)
            try
            {
                var maxValRange = Convert.ToInt32(rangeAttr.ConstructorArguments[1].Value);
                return CalculateBitsNeeded(maxValRange);
            }
            catch
            {
            }

        var maxEnumVal = 1;
        foreach (var member in enumType.GetMembers().OfType<IFieldSymbol>())
            if (member.HasConstantValue)
                try
                {
                    var val = Convert.ToInt32(member.ConstantValue);
                    if (val > maxEnumVal) maxEnumVal = val;
                }
                catch
                {
                }

        return CalculateBitsNeeded(maxEnumVal);
    }

    private static int GetNumericBits(ITypeSymbol propType, ISymbol symbol, out bool hasConstraint, out long minVal,
        out long maxVal)
    {
        hasConstraint = false;
        minVal = 0;
        maxVal = 0;

        var rangeAttr = symbol.GetAttributes()
            .FirstOrDefault(a =>
                a.AttributeClass?.ToDisplayString() == "System.ComponentModel.DataAnnotations.RangeAttribute");

        if (rangeAttr != null && rangeAttr.ConstructorArguments.Length >= 2)
            try
            {
                hasConstraint = true;
                minVal = Convert.ToInt64(rangeAttr.ConstructorArguments[0].Value);
                maxVal = Convert.ToInt64(rangeAttr.ConstructorArguments[1].Value);

                var size = maxVal - minVal;
                return CalculateBitsNeeded((int)size);
            }
            catch
            {
            }

        return propType.SpecialType switch
        {
            SpecialType.System_Byte => 8,
            SpecialType.System_SByte => 8,
            SpecialType.System_Int16 => 16,
            SpecialType.System_UInt16 => 16,
            SpecialType.System_Int32 => 32,
            SpecialType.System_UInt32 => 32,
            SpecialType.System_Int64 => 64,
            SpecialType.System_UInt64 => 64,
            _ => 64
        };
    }

    private static int GetMaxLen(ISymbol symbol, out bool hasConstraint)
    {
        hasConstraint = false;

        var maxLengthAttr = symbol.GetAttributes()
            .FirstOrDefault(a =>
                a.AttributeClass?.ToDisplayString() == "System.ComponentModel.DataAnnotations.MaxLengthAttribute");

        if (maxLengthAttr != null && maxLengthAttr.ConstructorArguments.Length > 0 &&
            maxLengthAttr.ConstructorArguments[0].Value is int maxLenVal)
        {
            hasConstraint = true;
            return maxLenVal;
        }

        var stringLengthAttr = symbol.GetAttributes()
            .FirstOrDefault(a =>
                a.AttributeClass?.ToDisplayString() == "System.ComponentModel.DataAnnotations.StringLengthAttribute");

        if (stringLengthAttr != null && stringLengthAttr.ConstructorArguments.Length > 0 &&
            stringLengthAttr.ConstructorArguments[0].Value is int strLenVal)
        {
            hasConstraint = true;
            return strLenVal;
        }

        return 256; // default fallback string length
    }

    private static int CalculateBitsNeeded(int maxValue)
    {
        if (maxValue <= 0) return 1;
        return (int)Math.Ceiling(Math.Log(maxValue + 1, 2));
    }

    private static int GetPacketMaxBits(ITypeSymbol typeSymbol, List<SerializationTarget> targets, int packetMaxVersion)
    {
        return GetPacketMaxBits(typeSymbol, targets, packetMaxVersion, new HashSet<string>());
    }

    private static int GetPacketMaxBits(ITypeSymbol typeSymbol, List<SerializationTarget> targets, int packetMaxVersion,
        HashSet<string> seenTypes)
    {
        var typeKey = typeSymbol.ToDisplayString();
        if (!seenTypes.Add(typeKey)) return -1;

        var totalBits = packetMaxVersion > 1 ? 4 : 0;
        foreach (var target in targets)
        {
            if (GetPropertyVersion(target.Symbol) > packetMaxVersion) continue;

            var targetBits = GetTargetMaxBits(target, seenTypes);
            if (targetBits < 0)
            {
                seenTypes.Remove(typeKey);
                return -1;
            }

            totalBits += targetBits;
        }

        seenTypes.Remove(typeKey);
        return totalBits;
    }

    private static int GetTargetMaxBits(SerializationTarget target, HashSet<string> seenTypes)
    {
        var propType = target.Type;

        if (propType is IArrayTypeSymbol arrayType) return GetArrayMaxBits(target, arrayType, seenTypes);
        if (TryGetAngleConfig(propType, target.Symbol, out var angleConfig, out _)) return angleConfig.Bits;
        if (TryGetVectorRangeConfig(propType, target.Symbol, out var vectorConfig, out _))
            return (propType.ToDisplayString() == "System.Numerics.Vector3" ? 3 : 2) * vectorConfig.Bits;
        if (TryGetQuaternionSmallestThreeConfig(propType, target.Symbol, out var quaternionConfig, out _))
            return 2 + 3 * quaternionConfig.BitsPerComponent;
        if (propType.SpecialType == SpecialType.System_Boolean) return 1;
        if (propType.SpecialType == SpecialType.System_Char) return 16;
        if (propType.SpecialType == SpecialType.System_String)
        {
            var maxLen = GetMaxLen(target.Symbol, out _);
            var maxBytes = maxLen * 4;
            return CalculateBitsNeeded(maxBytes) + maxBytes * 8;
        }
        if (propType.ToDisplayString() == "System.DateTime") return 64;
        if (propType.TypeKind == TypeKind.Enum) return GetEnumBits(propType, target.Symbol);
        if (propType.SpecialType is SpecialType.System_Single or SpecialType.System_Double)
        {
            return GetQuantizationConfig(target.Symbol, out _, out _, out _, out _, out var bits)
                ? bits
                : propType.SpecialType == SpecialType.System_Single ? 32 : 64;
        }
        if (propType.SpecialType == SpecialType.System_Decimal) return 128;
        if (propType.ToDisplayString() == "nint" || propType.ToDisplayString() == "System.IntPtr" ||
            propType.ToDisplayString() == "nuint" || propType.ToDisplayString() == "System.UIntPtr")
            return GetNumericBits(propType, target.Symbol, out _, out _, out _);
        if (propType.TypeKind == TypeKind.Interface) return -1;
        if (IsBitPacketType(propType))
            return GetPacketMaxBits(propType, GetSerializationTargets(propType), GetPacketVersion(propType), seenTypes);
        if (ExposesCustomSerialization(propType, out _)) return -1;
        if (propType.SpecialType is SpecialType.System_UInt32 or SpecialType.System_UInt64 or SpecialType.System_SByte
            or SpecialType.System_Byte or SpecialType.System_Int16 or SpecialType.System_UInt16 or SpecialType.System_Int32
            or SpecialType.System_Int64)
            return GetNumericBits(propType, target.Symbol, out _, out _, out _);

        return -1;
    }

    private static int GetArrayMaxBits(SerializationTarget target, IArrayTypeSymbol arrayType, HashSet<string> seenTypes)
    {
        if (!TryGetArrayConfig(target.Symbol, arrayType, out var config, out _)) return -1;

        var elementTarget = new SerializationTarget($"{target.Name}Element", arrayType.ElementType, target.Symbol, null);
        var elementBits = GetTargetMaxBits(elementTarget, seenTypes);
        if (elementBits < 0) return -1;

        return config.IsFixed
            ? config.Count * elementBits
            : config.LengthBits + config.Count * elementBits;
    }

    private static string BuildLayoutManifest(ITypeSymbol typeSymbol, List<SerializationTarget> targets, int packetMaxVersion,
        int maxBits, int maxBytes)
    {
        var sb = new StringBuilder();
        sb.AppendLine($"type={typeSymbol.ToDisplayString()}");
        sb.AppendLine($"version={packetMaxVersion}");
        sb.AppendLine($"maxBits={maxBits}");
        sb.AppendLine($"maxBytes={maxBytes}");
        foreach (var target in targets)
        {
            var targetBits = GetTargetMaxBits(target, new HashSet<string> { typeSymbol.ToDisplayString() });
            sb.AppendLine(BuildLayoutManifestLine(target, targetBits));
        }

        return sb.ToString();
    }

    private static string BuildLayoutManifestLine(SerializationTarget target, int targetBits)
    {
        var line =
            $"field={target.Name};type={target.Type.ToDisplayString()};declaringType={target.Symbol.ContainingType.ToDisplayString()};key={target.FieldKey?.ToString() ?? ""};since={GetPropertyVersion(target.Symbol)}";

        line += GetCodecManifest(target.Type, target.Symbol);

        if (target.Type is IArrayTypeSymbol arrayType && TryGetArrayConfig(target.Symbol, arrayType, out var config, out _))
        {
            var elementTarget = new SerializationTarget($"{target.Name}Element", arrayType.ElementType, target.Symbol, null);
            var elementBits = GetTargetMaxBits(elementTarget, new HashSet<string>());
            line +=
                $";array={(config.IsFixed ? "fixed" : "max")};count={config.Count};elementType={arrayType.ElementType.ToDisplayString()};elementBits={elementBits}";
        }

        return $"{line};bits={targetBits}";
    }

    private static string GetCodecManifest(ITypeSymbol type, ISymbol symbol)
    {
        var effectiveType = type is IArrayTypeSymbol arrayType ? arrayType.ElementType : type;
        if (TryGetAngleConfig(effectiveType, symbol, out var angleConfig, out _))
            return $";codec=angle;codecBits={angleConfig.Bits}";
        if (TryGetVectorRangeConfig(effectiveType, symbol, out var vectorConfig, out _))
            return $";codec=vectorRange;min={vectorConfig.Min};max={vectorConfig.Max};decimals={vectorConfig.Decimals};componentBits={vectorConfig.Bits}";
        if (TryGetQuaternionSmallestThreeConfig(effectiveType, symbol, out var quaternionConfig, out _))
            return $";codec=quaternionSmallestThree;componentBits={quaternionConfig.BitsPerComponent}";

        return string.Empty;
    }

    private static uint ComputeFnv1A32(string value)
    {
        unchecked
        {
            const uint offsetBasis = 2166136261u;
            const uint prime = 16777619u;
            var hash = offsetBasis;
            foreach (var b in Encoding.UTF8.GetBytes(value))
            {
                hash ^= b;
                hash *= prime;
            }

            return hash;
        }
    }

    private static string EscapeStringLiteral(string value)
    {
        return value
            .Replace("\\", "\\\\")
            .Replace("\"", "\\\"")
            .Replace("\r", "\\r")
            .Replace("\n", "\\n");
    }

    private static void ReportError(SourceProductionContext context, ISymbol prop)
    {
        context.ReportDiagnostic(Diagnostic.Create(
            UnsupportedTypeError,
            prop.Locations.FirstOrDefault(),
            prop.Name,
            prop is IPropertySymbol p
                ? p.Type.ToDisplayString()
                : prop is IFieldSymbol f
                    ? f.Type.ToDisplayString()
                    : ""));
    }

    private static void ReportWarning(SourceProductionContext context, ISymbol prop)
    {
        context.ReportDiagnostic(Diagnostic.Create(
            UnconstrainedPropertyWarning,
            prop.Locations.FirstOrDefault(),
            prop.Name,
            prop is IPropertySymbol p
                ? p.Type.ToDisplayString()
                : prop is IFieldSymbol f
                    ? f.Type.ToDisplayString()
                    : ""));
    }

    private static int GetPacketVersion(ITypeSymbol typeSymbol)
    {
        var attr = typeSymbol.GetAttributes()
            .FirstOrDefault(a => a.AttributeClass?.ToDisplayString() == "BitPack.BitPacketAttribute");
        if (attr != null && attr.ConstructorArguments.Length > 0 &&
            attr.ConstructorArguments[0].Value is int v) return v;

        return 1;
    }

    private static int GetPropertyVersion(ISymbol symbol)
    {
        var attr = symbol.GetAttributes()
            .FirstOrDefault(a => a.AttributeClass?.ToDisplayString() == "BitPack.SinceVersionAttribute");
        if (attr != null && attr.ConstructorArguments.Length > 0 &&
            attr.ConstructorArguments[0].Value is int v) return v;

        return 1;
    }

    private class SerializationTarget
    {
        public SerializationTarget(string name, ITypeSymbol type, ISymbol symbol, int? fieldKey)
        {
            Name = name;
            Type = type;
            Symbol = symbol;
            FieldKey = fieldKey;
        }

        public string Name { get; }
        public ITypeSymbol Type { get; }
        public ISymbol Symbol { get; }
        public int? FieldKey { get; }
    }

    private readonly struct ArrayConfig
    {
        public ArrayConfig(bool isFixed, int count, int lengthBits)
        {
            IsFixed = isFixed;
            Count = count;
            LengthBits = lengthBits;
        }

        public bool IsFixed { get; }
        public int Count { get; }
        public int LengthBits { get; }
    }

    private readonly struct AngleConfig
    {
        public AngleConfig(int bits)
        {
            Bits = bits;
        }

        public int Bits { get; }
    }

    private readonly struct VectorRangeConfig
    {
        public VectorRangeConfig(double min, double max, int decimals, double scale, int bits)
        {
            Min = min;
            Max = max;
            Decimals = decimals;
            Scale = scale;
            Bits = bits;
        }

        public double Min { get; }
        public double Max { get; }
        public int Decimals { get; }
        public double Scale { get; }
        public int Bits { get; }
    }

    private readonly struct QuaternionSmallestThreeConfig
    {
        public QuaternionSmallestThreeConfig(int bitsPerComponent)
        {
            BitsPerComponent = bitsPerComponent;
        }

        public int BitsPerComponent { get; }
    }
}
