using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace BitPack.Generator;

[Generator]
public class PacketGenerator : IIncrementalGenerator
{
    private static readonly DiagnosticDescriptor UnsupportedTypeError = new(
        id: "BP0001",
        title: "Unsupported Property Type",
        messageFormat: "Property '{0}' of type '{1}' must be annotated with [BitPacket] or implement custom serialization (Serialize and static Deserialize)",
        category: "BitPackGenerator",
        defaultSeverity: DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    private static readonly DiagnosticDescriptor UnconstrainedPropertyWarning = new(
        id: "BP0002",
        title: "Unconstrained Property Warning",
        messageFormat: "Property '{0}' of type '{1}' does not specify a range or length attribute. Full type storage will be used, which is unoptimized.",
        category: "BitPackGenerator",
        defaultSeverity: DiagnosticSeverity.Warning,
        isEnabledByDefault: true);

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var packetDeclarations = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (s, _) => s is TypeDeclarationSyntax tds && tds.AttributeLists.Count > 0,
                transform: static (ctx, _) => GetSemanticTargetForGeneration(ctx))
            .Where(static m => m is not null);

        context.RegisterSourceOutput(packetDeclarations, static (spc, source) => Execute(spc, source!));
    }

    private static ITypeSymbol? GetSemanticTargetForGeneration(GeneratorSyntaxContext context)
    {
        var typeDeclarationSyntax = (TypeDeclarationSyntax)context.Node;

        foreach (var attributeListSyntax in typeDeclarationSyntax.AttributeLists)
        {
            foreach (var attributeSyntax in attributeListSyntax.Attributes)
            {
                var symbol = context.SemanticModel.GetSymbolInfo(attributeSyntax).Symbol;
                if (symbol is IMethodSymbol attributeConstructor)
                {
                    var attributeContainingTypeSymbol = attributeConstructor.ContainingType;
                    var fullName = attributeContainingTypeSymbol.ToDisplayString();

                    if (fullName == "BitPack.BitPacketAttribute")
                    {
                        return context.SemanticModel.GetDeclaredSymbol(typeDeclarationSyntax) as ITypeSymbol;
                    }
                }
            }
        }

        return null;
    }

    private static void Execute(SourceProductionContext context, ITypeSymbol typeSymbol)
    {
        var namespaceName = typeSymbol.ContainingNamespace.IsGlobalNamespace
            ? string.Empty
            : typeSymbol.ContainingNamespace.ToDisplayString();

        var typeName = typeSymbol.Name;
        
        var typeKeyword = "class";
        if (typeSymbol.IsRecord)
        {
            typeKeyword = typeSymbol.IsValueType ? "record struct" : "record";
        }
        else if (typeSymbol.IsValueType)
        {
            typeKeyword = "struct";
        }

        var targets = GetSerializationTargets(typeSymbol);
        ValidateTargetSafety(context, typeSymbol, targets);

        var sourceBuilder = new StringBuilder();
        sourceBuilder.AppendLine("// <auto-generated/>");
        sourceBuilder.AppendLine("using System;");
        sourceBuilder.AppendLine("using BitPack;");
        sourceBuilder.AppendLine();

        if (!string.IsNullOrEmpty(namespaceName))
        {
            sourceBuilder.AppendLine($"namespace {namespaceName};");
            sourceBuilder.AppendLine();
        }

        sourceBuilder.AppendLine($"public partial {typeKeyword} {typeName} : IBitSerializable");
        sourceBuilder.AppendLine("{");

        // Retrieve packet version
        var packetMaxVersion = GetPacketVersion(typeSymbol);

        // Generate Serialize method
        sourceBuilder.AppendLine("    public void Serialize(BitWriter writer)");
        sourceBuilder.AppendLine("    {");
        if (packetMaxVersion > 1)
        {
            sourceBuilder.AppendLine($"        writer.WriteInt({packetMaxVersion}, 4);");
        }
        GenerateSerializationLoop(context, sourceBuilder, typeSymbol, isWriting: true, packetMaxVersion);
        sourceBuilder.AppendLine("    }");
        sourceBuilder.AppendLine();

        // Generate Deserialize method
        sourceBuilder.AppendLine("    public void Deserialize(BitReader reader)");
        sourceBuilder.AppendLine("    {");
        if (packetMaxVersion > 1)
        {
            sourceBuilder.AppendLine("        var packetVersion = reader.ReadInt(4);");
        }
        GenerateSerializationLoop(context, sourceBuilder, typeSymbol, isWriting: false, packetMaxVersion);
        sourceBuilder.AppendLine("    }");



        // Generate static Read factory method (enables clean nested deserialization)
        sourceBuilder.AppendLine();
        sourceBuilder.AppendLine($"    public static {typeName} Read(BitReader reader)");
        sourceBuilder.AppendLine("    {");
        if (packetMaxVersion > 1)
        {
            sourceBuilder.AppendLine("        var packetVersion = reader.ReadInt(4);");
        }
        else
        {
            sourceBuilder.AppendLine("        var packetVersion = 1;");
        }

        // 1. Declare read variables with defaults
        foreach (var target in targets)
        {
            sourceBuilder.AppendLine($"        var read_{target.Name} = default({target.Type.ToDisplayString()});");
        }
        sourceBuilder.AppendLine();

        // 2. Read variables from bitstream using target-agnostic generator
        foreach (var target in targets)
        {
            var propVersion = GetPropertyVersion(target.Symbol);
            var propSb = new StringBuilder();
            GeneratePropertySerialization(context, propSb, target, isWriting: false, $"read_{target.Name}");

            if (propVersion > 1)
            {
                sourceBuilder.AppendLine($"        if (packetVersion >= {propVersion})");
                sourceBuilder.AppendLine("        {");
                foreach (var line in propSb.ToString().Split(new[] { "\r\n", "\n" }, StringSplitOptions.None))
                {
                    if (!string.IsNullOrWhiteSpace(line))
                        sourceBuilder.AppendLine("    " + line);
                }
                sourceBuilder.AppendLine("        }");
            }
            else
            {
                sourceBuilder.Append(propSb.ToString());
            }
        }
        sourceBuilder.AppendLine();

        // 3. Resolve constructor
        var ctor = FindMatchingConstructor(typeSymbol as INamedTypeSymbol, targets, out var ctorArgs);
        if (ctor != null)
        {
            sourceBuilder.Append($"        var packet = new {typeName}(");
            for (var i = 0; i < ctorArgs.Count; i++)
            {
                sourceBuilder.Append($"read_{ctorArgs[i].Name}");
                if (i < ctorArgs.Count - 1)
                    sourceBuilder.Append(", ");
            }
            sourceBuilder.AppendLine(")");
            sourceBuilder.AppendLine("        {");
            foreach (var target in targets)
            {
                if (!ctorArgs.Contains(target) && IsWritablePropertyForInitializer(target.Symbol))
                {
                    sourceBuilder.AppendLine($"            {target.Name} = read_{target.Name},");
                }
            }
            sourceBuilder.AppendLine("        };");
        }
        else
        {
            sourceBuilder.AppendLine($"        var packet = new {typeName}");
            sourceBuilder.AppendLine("        {");
            foreach (var target in targets)
            {
                if (IsWritablePropertyForInitializer(target.Symbol))
                {
                    sourceBuilder.AppendLine($"            {target.Name} = read_{target.Name},");
                }
            }
            sourceBuilder.AppendLine("        };");
        }

        sourceBuilder.AppendLine("        return packet;");
        sourceBuilder.AppendLine("    }");

        sourceBuilder.AppendLine("}");

        context.AddSource($"{typeName}.g.cs", SourceText.From(sourceBuilder.ToString(), Encoding.UTF8));
    }

    private class SerializationTarget
    {
        public string Name { get; }
        public ITypeSymbol Type { get; }
        public ISymbol Symbol { get; }

        public SerializationTarget(string name, ITypeSymbol type, ISymbol symbol)
        {
            Name = name;
            Type = type;
            Symbol = symbol;
        }
    }

    private static bool HasIgnoreAttribute(ISymbol symbol)
    {
        return symbol.GetAttributes().Any(a => 
            a.AttributeClass?.ToDisplayString() == "System.Text.Json.Serialization.JsonIgnoreAttribute" ||
            a.AttributeClass?.ToDisplayString() == "System.Runtime.Serialization.IgnoreDataMemberAttribute");
    }

    private static bool HasIncludeAttribute(ISymbol symbol)
    {
        return symbol.GetAttributes().Any(a => 
            a.AttributeClass?.ToDisplayString() == "System.Runtime.Serialization.DataMemberAttribute");
    }

    private static List<SerializationTarget> GetSerializationTargets(ITypeSymbol typeSymbol)
    {
        var targets = new List<SerializationTarget>();

        foreach (var member in typeSymbol.GetMembers())
        {
            if (member.IsStatic) continue;

            if (member is IPropertySymbol p)
            {
                var isPublic = p.DeclaredAccessibility == Accessibility.Public;
                var hasInclude = HasIncludeAttribute(p);
                var hasIgnore = HasIgnoreAttribute(p);

                if ((isPublic && !hasIgnore) || (!isPublic && hasInclude))
                {
                    targets.Add(new SerializationTarget(p.Name, p.Type, p));
                }
            }
            else if (member is IFieldSymbol f && !f.IsImplicitlyDeclared)
            {
                var hasInclude = HasIncludeAttribute(f);
                if (hasInclude)
                {
                    targets.Add(new SerializationTarget(f.Name, f.Type, f));
                }
            }
        }

        return targets;
    }

    private static void ValidateTargetSafety(SourceProductionContext context, ITypeSymbol typeSymbol, List<SerializationTarget> targets)
    {
        var namedType = typeSymbol as INamedTypeSymbol;
        
        foreach (var target in targets)
        {
            if (target.Symbol is IPropertySymbol p)
            {
                // 1. Check getter accessor
                if (p.GetMethod == null)
                {
                    context.ReportDiagnostic(Diagnostic.Create(
                        UnsupportedTypeError,
                        p.Locations.FirstOrDefault(),
                        p.Name,
                        $"Property '{p.Name}' must have a getter accessor to be serialized."));
                }

                // 2. Check setter/init or constructor match
                if (p.SetMethod == null)
                {
                    var hasMatchingCtorParam = false;
                    if (namedType != null)
                    {
                        foreach (var ctor in namedType.InstanceConstructors)
                        {
                            if (ctor.Parameters.Any(param => string.Equals(param.Name, p.Name, StringComparison.OrdinalIgnoreCase)))
                            {
                                hasMatchingCtorParam = true;
                                break;
                            }
                        }
                    }

                    if (!hasMatchingCtorParam)
                    {
                        context.ReportDiagnostic(Diagnostic.Create(
                            UnsupportedTypeError,
                            p.Locations.FirstOrDefault(),
                            p.Name,
                            $"Property '{p.Name}' must have a setter or init accessor, or match a constructor parameter to be deserialized."));
                    }
                }
            }
        }
    }

    private static IMethodSymbol? FindMatchingConstructor(INamedTypeSymbol? typeSymbol, List<SerializationTarget> targets, out List<SerializationTarget> ctorArgs)
    {
        ctorArgs = new List<SerializationTarget>();
        if (typeSymbol == null) return null;
        var ctors = typeSymbol.InstanceConstructors
            .Where(c => c.DeclaredAccessibility == Accessibility.Public || c.DeclaredAccessibility == Accessibility.Internal)
            .OrderByDescending(c => c.Parameters.Length);

        foreach (var ctor in ctors)
        {
            if (ctor.Parameters.Length == 0) continue;

            var matchedArgs = new List<SerializationTarget>();
            var allMatched = true;

            foreach (var param in ctor.Parameters)
            {
                var target = targets.FirstOrDefault(t => string.Equals(t.Name, param.Name, StringComparison.OrdinalIgnoreCase));
                if (target != null)
                {
                    matchedArgs.Add(target);
                }
                else
                {
                    allMatched = false;
                    break;
                }
            }

            if (allMatched)
            {
                ctorArgs = matchedArgs;
                return ctor;
            }
        }

        return null;
    }

    private static bool IsWritableProperty(ISymbol symbol)
    {
        if (symbol is IFieldSymbol) return true;
        if (symbol is IPropertySymbol p)
        {
            return p.SetMethod != null && !p.SetMethod.IsInitOnly;
        }
        return false;
    }

    private static bool IsWritablePropertyForInitializer(ISymbol symbol)
    {
        if (symbol is IFieldSymbol) return true;
        if (symbol is IPropertySymbol p)
        {
            return p.SetMethod != null;
        }
        return false;
    }

    private static void GenerateSerializationLoop(SourceProductionContext context, StringBuilder sb, ITypeSymbol typeSymbol, bool isWriting, int packetMaxVersion)
    {
        var targets = GetSerializationTargets(typeSymbol);

        foreach (var target in targets)
        {
            var propVersion = GetPropertyVersion(target.Symbol);
            if (propVersion > packetMaxVersion)
            {
                context.ReportDiagnostic(Diagnostic.Create(
                    UnsupportedTypeError,
                    target.Symbol.Locations.FirstOrDefault(),
                    target.Name,
                    $"Property version {propVersion} exceeds packet version {packetMaxVersion}."));
            }

            var propSb = new StringBuilder();
            
            if (isWriting)
            {
                GeneratePropertySerialization(context, propSb, target, isWriting: true, $"this.{target.Name}");
            }
            else
            {
                if (IsWritableProperty(target.Symbol))
                {
                    GeneratePropertySerialization(context, propSb, target, isWriting: false, $"this.{target.Name}");
                }
                else
                {
                    propSb.AppendLine($"        // Read and discard init-only / read-only property '{target.Name}' during instance Deserialize");
                    propSb.AppendLine($"        {target.Type.ToDisplayString()} discard_{target.Name};");
                    GeneratePropertySerialization(context, propSb, target, isWriting: false, $"discard_{target.Name}");
                }
            }

            if (!isWriting && propVersion > 1)
            {
                sb.AppendLine($"        if (packetVersion >= {propVersion})");
                sb.AppendLine("        {");
                var lines = propSb.ToString().Split(new[] { "\r\n", "\n" }, StringSplitOptions.None);
                foreach (var line in lines)
                {
                    if (!string.IsNullOrWhiteSpace(line))
                        sb.AppendLine("    " + line);
                }
                sb.AppendLine("        }");
            }
            else
            {
                sb.Append(propSb.ToString());
            }
        }
    }

    private static void GeneratePropertySerialization(SourceProductionContext context, StringBuilder sb, SerializationTarget target, bool isWriting, string targetVarName)
    {
        var propName = targetVarName;
        var propType = target.Type;

        // Check for custom serialization or bit packet nested properties
        var isBitPacket = IsBitPacketType(propType);
        var hasCustom = ExposesCustomSerialization(propType, out var staticMethodName);

        // 1. Boolean
        if (propType.SpecialType == SpecialType.System_Boolean)
        {
            if (isWriting)
                sb.AppendLine($"        writer.WriteBool({propName});");
            else
                sb.AppendLine($"        {propName} = reader.ReadBool();");
        }
        // 2. Char
        else if (propType.SpecialType == SpecialType.System_Char)
        {
            if (isWriting)
                sb.AppendLine($"        writer.WriteInt((int){propName}, 16);");
            else
                sb.AppendLine($"        {propName} = (char)reader.ReadInt(16);");
        }
        // 3. String
        else if (propType.SpecialType == SpecialType.System_String)
        {
            var maxLen = GetMaxLen(target.Symbol, out var hasConstraint);
            if (!hasConstraint && isWriting)
            {
                ReportWarning(context, target.Symbol);
            }

            if (isWriting)
                sb.AppendLine($"        writer.WriteString({propName}, {maxLen});");
            else
                sb.AppendLine($"        {propName} = reader.ReadString({maxLen});");
        }
        // 4. DateTime
        else if (propType.ToDisplayString() == "System.DateTime")
        {
            if (isWriting)
                sb.AppendLine($"        writer.WriteDateTime({propName});");
            else
                sb.AppendLine($"        {propName} = reader.ReadDateTime();");
        }
        // 5. Enum
        else if (propType.TypeKind == TypeKind.Enum)
        {
            var bits = GetEnumBits(propType, target.Symbol);
            if (isWriting)
            {
                sb.AppendLine($"        writer.WriteInt((int){propName}, {bits});");
            }
            else
            {
                var enumFields = propType.GetMembers().OfType<IFieldSymbol>().Where(f => f.HasConstantValue).ToList();
                var enumTypeName = propType.ToDisplayString();
                sb.AppendLine($"        var temp{target.Name} = reader.ReadInt({bits});");
                sb.AppendLine($"        {propName} = temp{target.Name} switch");
                sb.AppendLine("        {");
                long defaultVal = 0;
                bool hasZero = false;
                foreach (var field in enumFields)
                {
                    var val = Convert.ToInt64(field.ConstantValue);
                    if (val == 0) hasZero = true;
                    sb.AppendLine($"            {val} => ({enumTypeName}){val},");
                }
                if (!hasZero && enumFields.Count > 0)
                {
                    defaultVal = Convert.ToInt64(enumFields[0].ConstantValue);
                }
                sb.AppendLine($"            _ => ({enumTypeName}){defaultVal}");
                sb.AppendLine("        };");
            }
        }
        // 6. Floating-point (float, double) with fixed-point quantization
        else if (propType.SpecialType == SpecialType.System_Single || propType.SpecialType == SpecialType.System_Double)
        {
            var isQuantized = GetQuantizationConfig(target.Symbol, out var minVal, out var maxVal, out var decimals, out var scale, out var bits);
            
            if (isQuantized)
            {
                var castStr = propType.SpecialType == SpecialType.System_Single ? "float" : "double";
                if (isWriting)
                    sb.AppendLine($"        writer.WriteLong((long)(({propName} - ({minVal})) * {scale}d + 0.5d), {bits});");
                else
                    sb.AppendLine($"        {propName} = ({castStr})((double)reader.ReadLong({bits}) / {scale}d + ({minVal}));");
            }
            else
            {
                // Fall back to full float/double representation
                if (isWriting)
                {
                    ReportWarning(context, target.Symbol);
                    if (propType.SpecialType == SpecialType.System_Single)
                        sb.AppendLine($"        writer.WriteFloat({propName});");
                    else
                        sb.AppendLine($"        writer.WriteDouble({propName});");
                }
                else
                {
                    if (propType.SpecialType == SpecialType.System_Single)
                        sb.AppendLine($"        {propName} = reader.ReadFloat();");
                    else
                        sb.AppendLine($"        {propName} = reader.ReadDouble();");
                }
            }
        }
        // 6.5. Decimal
        else if (propType.SpecialType == SpecialType.System_Decimal)
        {
            if (isWriting)
                sb.AppendLine($"        writer.WriteDecimal({propName});");
            else
                sb.AppendLine($"        {propName} = reader.ReadDecimal();");
        }
        // 6.6. Native integers (nint, nuint, IntPtr, UIntPtr)
        else if (propType.ToDisplayString() == "nint" || propType.ToDisplayString() == "System.IntPtr")
        {
            var bits = GetNumericBits(propType, target.Symbol, out var hasConstraint, out var minVal, out var maxVal);
            if (isWriting)
            {
                if (hasConstraint)
                    sb.AppendLine($"        writer.WriteLong((long)({propName} - ({minVal})), {bits});");
                else
                    sb.AppendLine($"        writer.WriteLong((long){propName}, {bits});");
            }
            else
            {
                if (hasConstraint)
                    sb.AppendLine($"        {propName} = (nint)(reader.ReadLong({bits}) + ({minVal}));");
                else
                    sb.AppendLine($"        {propName} = (nint)reader.ReadLong({bits});");
            }
        }
        else if (propType.ToDisplayString() == "nuint" || propType.ToDisplayString() == "System.UIntPtr")
        {
            var bits = GetNumericBits(propType, target.Symbol, out var hasConstraint, out var minVal, out var maxVal);
            if (isWriting)
            {
                if (hasConstraint)
                    sb.AppendLine($"        writer.WriteULong((ulong)({propName} - ({minVal})), {bits});");
                else
                    sb.AppendLine($"        writer.WriteULong((ulong){propName}, {bits});");
            }
            else
            {
                if (hasConstraint)
                    sb.AppendLine($"        {propName} = (nuint)(reader.ReadULong({bits}) + ({minVal}));");
                else
                    sb.AppendLine($"        {propName} = (nuint)reader.ReadULong({bits});");
            }
        }
        // 6.7. Interface Types
        else if (propType.TypeKind == TypeKind.Interface)
        {
            var implementsBitSerializable = propType.AllInterfaces.Any(i => i.ToDisplayString() == "BitPack.IBitSerializable") || propType.ToDisplayString() == "BitPack.IBitSerializable";
            if (implementsBitSerializable)
            {
                if (isWriting)
                    sb.AppendLine($"        {propName}.Serialize(writer);");
                else
                    sb.AppendLine($"        {propName}.Deserialize(reader);");
            }
            else
            {
                if (isWriting)
                    ReportError(context, target.Symbol);
                sb.AppendLine($"        // ERROR: Interface property '{propName}' of type '{propType.ToDisplayString()}' must implement IBitSerializable.");
            }
        }
        // 7. Nested Packets or Custom Value Objects
        else if (isBitPacket || hasCustom)
        {
            if (isWriting)
            {
                sb.AppendLine($"        {propName}.Serialize(writer);");
            }
            else
            {
                if (isBitPacket)
                {
                    sb.AppendLine($"        {propName} = {propType.ToDisplayString()}.Read(reader);");
                }
                else if (staticMethodName != null)
                {
                    sb.AppendLine($"        {propName} = {propType.ToDisplayString()}.{staticMethodName}(reader);");
                }
                else
                {
                    sb.AppendLine($"        {propName} = new {propType.ToDisplayString()}();");
                    sb.AppendLine($"        {propName}.Deserialize(reader);");
                }
            }
        }
        // 8. Unsigned integers (uint, ulong)
        else if (propType.SpecialType == SpecialType.System_UInt32 || propType.SpecialType == SpecialType.System_UInt64)
        {
            var bits = GetNumericBits(propType, target.Symbol, out var hasConstraint, out var minVal, out var maxVal);
            if (!hasConstraint && isWriting)
            {
                ReportWarning(context, target.Symbol);
            }

            if (isWriting)
            {
                if (hasConstraint)
                    sb.AppendLine($"        writer.WriteULong((ulong)({propName} - ({minVal})), {bits});");
                else
                    sb.AppendLine($"        writer.WriteULong((ulong){propName}, {bits});");
            }
            else
            {
                if (hasConstraint)
                    sb.AppendLine($"        {propName} = ({propType.ToDisplayString()})(reader.ReadULong({bits}) + ({minVal}));");
                else
                    sb.AppendLine($"        {propName} = ({propType.ToDisplayString()})reader.ReadULong({bits});");
            }
        }
        // 9. Signed or small integers (sbyte, byte, short, ushort, int, long)
        else if (propType.SpecialType == SpecialType.System_SByte ||
                 propType.SpecialType == SpecialType.System_Byte ||
                 propType.SpecialType == SpecialType.System_Int16 ||
                 propType.SpecialType == SpecialType.System_UInt16 ||
                 propType.SpecialType == SpecialType.System_Int32 ||
                 propType.SpecialType == SpecialType.System_Int64)
        {
            var bits = GetNumericBits(propType, target.Symbol, out var hasConstraint, out var minVal, out var maxVal);
            if (!hasConstraint && isWriting)
            {
                ReportWarning(context, target.Symbol);
            }

            if (isWriting)
            {
                if (hasConstraint)
                    sb.AppendLine($"        writer.WriteLong((long)({propName} - ({minVal})), {bits});");
                else
                    sb.AppendLine($"        writer.WriteLong((long){propName}, {bits});");
            }
            else
            {
                if (hasConstraint)
                    sb.AppendLine($"        {propName} = ({propType.ToDisplayString()})(reader.ReadLong({bits}) + ({minVal}));");
                else
                    sb.AppendLine($"        {propName} = ({propType.ToDisplayString()})reader.ReadLong({bits});");
            }
        }
        // 10. Unsupported complex structures (raise build-time Error BP0001)
        else
        {
            if (isWriting)
            {
                ReportError(context, target.Symbol);
            }
            sb.AppendLine($"        // ERROR: Property '{propName}' of type '{propType.ToDisplayString()}' is not packable.");
        }
    }

    private static bool IsBitPacketType(ITypeSymbol type)
    {
        return type.GetAttributes().Any(a => 
            a.AttributeClass?.ToDisplayString() == "BitPack.BitPacketAttribute");
    }

    private static bool ExposesCustomSerialization(ITypeSymbol type, out string? staticMethodName)
    {
        var members = type.GetMembers();
        var hasSerialize = members.OfType<IMethodSymbol>().Any(m => 
            m.Name == "Serialize" && 
            m.Parameters.Length == 1 && 
            m.Parameters[0].Type.ToDisplayString() == "BitPack.BitWriter");

        var staticDeserializer = members.OfType<IMethodSymbol>().FirstOrDefault(m => 
            m.IsStatic && 
            (m.Name == "Deserialize" || m.Name == "Read") && 
            m.Parameters.Length == 1 && 
            m.Parameters[0].Type.ToDisplayString() == "BitPack.BitReader" &&
            SymbolEqualityComparer.Default.Equals(m.ReturnType, type));

        staticMethodName = staticDeserializer?.Name;
        return hasSerialize;
    }

    private static bool GetQuantizationConfig(ISymbol symbol, out double minVal, out double maxVal, out int decimals, out double scale, out int bits)
    {
        minVal = 0;
        maxVal = 0;
        decimals = 0;
        scale = 1;
        bits = 32;

        var rangeAttr = symbol.GetAttributes()
            .FirstOrDefault(a => a.AttributeClass?.ToDisplayString() == "System.ComponentModel.DataAnnotations.RangeAttribute");

        var precisionAttr = symbol.GetAttributes()
            .FirstOrDefault(a => a.AttributeClass?.ToDisplayString() == "BitPack.PrecisionAttribute");

        if (rangeAttr != null && precisionAttr != null && rangeAttr.ConstructorArguments.Length >= 2 && precisionAttr.ConstructorArguments.Length > 0)
        {
            try
            {
                minVal = Convert.ToDouble(rangeAttr.ConstructorArguments[0].Value);
                maxVal = Convert.ToDouble(rangeAttr.ConstructorArguments[1].Value);
                decimals = Convert.ToInt32(precisionAttr.ConstructorArguments[0].Value);

                scale = Math.Pow(10, decimals);
                var rangeSize = (maxVal - minVal) * scale;
                bits = (int)Math.Ceiling(Math.Log(rangeSize + 1, 2));
                return true;
            }
            catch { }
        }

        return false;
    }

    private static int GetEnumBits(ITypeSymbol enumType, ISymbol symbol)
    {

        var rangeAttr = symbol.GetAttributes()
            .FirstOrDefault(a => a.AttributeClass?.ToDisplayString() == "System.ComponentModel.DataAnnotations.RangeAttribute");

        if (rangeAttr != null && rangeAttr.ConstructorArguments.Length >= 2)
        {
            try
            {
                var maxValRange = Convert.ToInt32(rangeAttr.ConstructorArguments[1].Value);
                return CalculateBitsNeeded(maxValRange);
            }
            catch { }
        }

        var maxEnumVal = 1;
        foreach (var member in enumType.GetMembers().OfType<IFieldSymbol>())
        {
            if (member.HasConstantValue)
            {
                try
                {
                    var val = Convert.ToInt32(member.ConstantValue);
                    if (val > maxEnumVal) maxEnumVal = val;
                }
                catch { }
            }
        }

        return CalculateBitsNeeded(maxEnumVal);
    }

    private static int GetNumericBits(ITypeSymbol propType, ISymbol symbol, out bool hasConstraint, out long minVal, out long maxVal)
    {
        hasConstraint = false;
        minVal = 0;
        maxVal = 0;

        var rangeAttr = symbol.GetAttributes()
            .FirstOrDefault(a => a.AttributeClass?.ToDisplayString() == "System.ComponentModel.DataAnnotations.RangeAttribute");

        if (rangeAttr != null && rangeAttr.ConstructorArguments.Length >= 2)
        {
            try
            {
                hasConstraint = true;
                minVal = Convert.ToInt64(rangeAttr.ConstructorArguments[0].Value);
                maxVal = Convert.ToInt64(rangeAttr.ConstructorArguments[1].Value);
                
                var size = maxVal - minVal;
                return CalculateBitsNeeded((int)size);
            }
            catch { }
        }

        return propType.SpecialType switch
        {
            SpecialType.System_Byte => 8,
            SpecialType.System_SByte => 8,
            SpecialType.System_Int16 => 16,
            SpecialType.System_UInt16 => 16,
            SpecialType.System_Int32 => 32,
            SpecialType.System_UInt32 => 32,
            SpecialType.System_Int64 => 64,
            SpecialType.System_UInt64 => 64,
            _ => 64
        };
    }

    private static int GetMaxLen(ISymbol symbol, out bool hasConstraint)
    {
        hasConstraint = false;

        var maxLengthAttr = symbol.GetAttributes()
            .FirstOrDefault(a => a.AttributeClass?.ToDisplayString() == "System.ComponentModel.DataAnnotations.MaxLengthAttribute");

        if (maxLengthAttr != null && maxLengthAttr.ConstructorArguments.Length > 0 && maxLengthAttr.ConstructorArguments[0].Value is int maxLenVal)
        {
            hasConstraint = true;
            return maxLenVal;
        }

        var stringLengthAttr = symbol.GetAttributes()
            .FirstOrDefault(a => a.AttributeClass?.ToDisplayString() == "System.ComponentModel.DataAnnotations.StringLengthAttribute");

        if (stringLengthAttr != null && stringLengthAttr.ConstructorArguments.Length > 0 && stringLengthAttr.ConstructorArguments[0].Value is int strLenVal)
        {
            hasConstraint = true;
            return strLenVal;
        }

        return 256; // default fallback string length
    }

    private static int CalculateBitsNeeded(int maxValue)
    {
        if (maxValue <= 0) return 1;
        return (int)Math.Ceiling(Math.Log(maxValue + 1, 2));
    }

    private static void ReportError(SourceProductionContext context, ISymbol prop)
    {
        context.ReportDiagnostic(Diagnostic.Create(
            UnsupportedTypeError,
            prop.Locations.FirstOrDefault(),
            prop.Name,
            prop is IPropertySymbol p ? p.Type.ToDisplayString() : (prop is IFieldSymbol f ? f.Type.ToDisplayString() : "")));
    }

    private static void ReportWarning(SourceProductionContext context, ISymbol prop)
    {
        context.ReportDiagnostic(Diagnostic.Create(
            UnconstrainedPropertyWarning,
            prop.Locations.FirstOrDefault(),
            prop.Name,
            prop is IPropertySymbol p ? p.Type.ToDisplayString() : (prop is IFieldSymbol f ? f.Type.ToDisplayString() : "")));
    }

    private static int GetPacketVersion(ITypeSymbol typeSymbol)
    {
        var attr = typeSymbol.GetAttributes()
            .FirstOrDefault(a => a.AttributeClass?.ToDisplayString() == "BitPack.BitPacketAttribute");
        if (attr != null && attr.ConstructorArguments.Length > 0 && attr.ConstructorArguments[0].Value is int v)
        {
            return v;
        }
        return 1;
    }

    private static int GetPropertyVersion(ISymbol symbol)
    {
        var attr = symbol.GetAttributes()
            .FirstOrDefault(a => a.AttributeClass?.ToDisplayString() == "BitPack.SinceVersionAttribute");
        if (attr != null && attr.ConstructorArguments.Length > 0 && attr.ConstructorArguments[0].Value is int v)
        {
            return v;
        }
        return 1;
    }
}
